### ISSUE TITLE
Parallax & featherlight layering issues

### ISSUE THREAD

**Issue by danielsailes** [noelboss/featherlight#105]
A website i'm working on has a page with parallax elements through the page, a preview/gallery button is nestled inbetween 2 parallax elements. When i click on it nothing appears - i had assumed somehow i'd broke the code but it was working fine. Only trouble is I can only see it at the very bottom of the page past the parallax.

Any ideas? If anyone can help or needs to see the site i'll need to send it via private message as it's a staging server

**Comment by marcandre** [comment]
Sorry for not answering before. I imagine that either the CSS is not loaded, or `featherlight`'s div is not the last in the page, in which case you should provide a `root`.
