### ISSUE TITLE
Code validation

### ISSUE THREAD

**Issue by LucaNonato** [noelboss/featherlight#109]
Hi! I think featherlight is a great lightbox and i would like to use it, but the code it needs does not pass HTML 4.01 Transitional validation (At least when using 'data-featherlight="image"' within a HREF): do i need a different doctype or do i have to deal with it? :)

Cheers!
Luca

**Comment by marcandre** [comment]
Please provide me with a complete example I can copy-paste to http://validator.w3.org/check to see what you are talking about.

**Comment by LucaNonato** [comment]
On Sat, Jan 17, 2015 at 5:18 PM, Marc-André Lafortune
<notifications@github.com> wrote:
> Please provide me with a complete example I can copy-paste to http://validator.w3.org/check to see what you are talking about

You can use my website <http://www.lionscorassori.it>: this is
properly validated, but not using featherlight
<http://www.lionscorassori.it/notvalid.php> (This is a clone of index
page, the only difference is the featherlight use when clicking on
"gongoliamo", a link to an image).

Does make sense? If there's anything else i can do, just ask.


Cheers!
Luca

**Comment by marcandre** [comment]
Oh, right!

`data-` attributes are from the html 5 spec, so yeah, [they won't validate](http://stackoverflow.com/questions/5827697/jquery-data-attribute-doesnt-w3c-validate).
They [won't break](http://stackoverflow.com/questions/3957867/is-there-any-problem-with-using-html5s-data-attributes-for-older-browsers) anything either, but if you want to validate your page, then you will have to either set it as html 5, or else use the javascript API.
HTH
