### ISSUE TITLE
defaults.closeIcon HTML doesn't bubble

### ISSUE THREAD

**Issue by axebox** [noelboss/featherlight#112]
When using custom close button HTML (see below), Featherlight doesn't bubble up to .featherlight-close to allow the modal to close.

```Javascript
$.featherlight.defaults.closeIcon = '<span class="fa fa-close"></span>'
```

**Comment by marcandre** [comment]
Could you please provide a complete example (as requested in the [contributing guidelines](https://github.com/noelboss/featherlight#reporting-bugs-and-issues))

**Comment by axebox** [comment]
I'm not sure there's more to elaborate. This is the only configuring I've done so far.

**Comment by marcandre** [comment]
Wouldn't that replace the 'x' with an empty span?

**Comment by axebox** [comment]
.fa and .fa-close are font awesome classes. Identical to the icons (HTML/CSS) here:

http://fortawesome.github.io/Font-Awesome/icons/

**Comment by marcandre** [comment]
Then I'll repeat, would you please provide me with a working example, with the font-awesome resource linked and everything else you might need, so I don't have to guess things like this.
This is especially true for this issue which I don't see how or why it wouldn't work, nor am I sure what you mean by "doesn't bubble up".
In short, when reporting problems (for this project or any other), always make it very simple for the volunteers to reproduce your issue. This is especially easy to do with tools like jsfiddle.

**Comment by marcandre** [comment]
Oh, I see now.
Fixed and released.
Thanks for reporting this
