### ISSUE TITLE
The class featherlight closes

### ISSUE THREAD

**Issue by iainacton** [noelboss/featherlight#118]
Hi Marc-André,

I'm using the same code on both of these pages. The link 'About / Contact' is triggering Featherlight.

http://visualists.co.uk/ - Everything works perfectly here

http://visualistss.tumblr.com/ - I'm having some trouble with .featherlight (I think it's this, maybe not) breaking/disappearing and I'm not sure why. If you wait a few extra seconds before clicking 'About / Contact' so I'm guessing that it's breaking because something hasn't finished loading.

Thanks!

**Comment by marcandre** [comment]
I'm afraid I can't support everyone that develops using featherlight, for free, so that their stuff works.
You'll have to investigate this yourself, or find someone who will...
