### ISSUE TITLE
Swipe on touch devices

### ISSUE THREAD

**Issue by landwire** [noelboss/featherlight#119]
Hi there,

I loaded hammer.js and also tried another swipe library TouchSwipe, but none of them work out of the box. See this fiddle:

http://jsfiddle.net/JNsu6/39/

When I just use jQuery Mobile under "Frameworks" it works fine: http://jsfiddle.net/JNsu6/40/ 

Would I have to initialise hammer.js somehow for it to work with featherlight? If yes, how?
Thanks,
Sascha

**Comment by marcandre** [comment]
Sorry for the problems you're having, and thanks for including a fiddle.

You must load the swipe library before featherlight.

I'm having trouble with hammer which I'm trying to fix, but if you use the jquery lib you should be Ok.

**Comment by landwire** [comment]
Ah, ok! Of course. I was loading the swipe library after by accident. I just stick with jQuery Touch for now.
That seems to work ok. Though it’s a bit annoying on my iPhone as the page in the browser moves in the direction of the swipe when I swipe an image. Maybe it’s not such a good idea to have swipe enabled?
I guess there is no way of preventing that?
S

**Comment by marcandre** [comment]
Mmm, there should be a way to prevent that. It's the default with https://github.com/marcandre/detect_swipe so maybe you want to use that.

**Comment by landwire** [comment]
ok, I will try that! Yes, I am using a slider plugin, that also enables swipe on touch devices and the page does not move with that one. So it’s definitely possible.
thanks for your kind help and advice and a beautifully lightweight plugin - at least from what I can judge - but I am not great with jQuery!
S

**Comment by marcandre** [comment]
Ok, we're now compatible with Hammer, for real.
Released v1.2.2.

**Comment by landwire** [comment]
Well done!
So, all I need to do is load Hammer before Featherlight? No additional set-up?
S

**Comment by marcandre** [comment]
That's right.
If you don't need `Hammer`, though, `detectSwipe` is ~75 lines of code, vs ~2500 for `Hammer`...
