### ISSUE TITLE
slight cut off on smaller screens

### ISSUE THREAD

**Issue by Kryptonit3** [noelboss/featherlight#123]
![image](https://cloud.githubusercontent.com/assets/5751754/6740120/fa582494-ce53-11e4-9239-6a6fb8e579b8.png)

![image](https://cloud.githubusercontent.com/assets/5751754/6740378/bb84ad94-ce55-11e4-8036-d7fb2ab9b9cc.png)

**Comment by marcandre** [comment]
Thanks for the images.
Are you using Bootstrap 3.3.2 ? If so, it's probably [#117]
Otherwise, please **provide a working example** starting from [this jsfiddle](http://jsfiddle.net/JNsu6/15/).

**Comment by Kryptonit3** [comment]
Is this issue persistent with 3.3.4 (latest)? I am using 3.3.1 (css) 3.3.2 (js). Will try 3.3.4 if it solves issue.

**Comment by Kryptonit3** [comment]
looks like 3.3.4 is affected as well - http://jsfiddle.net/JNsu6/44/

**Comment by Kryptonit3** [comment]
the css provided in #117 does seem to fix the problem.

**Comment by marcandre** [comment]
Great, thanks for checking.
I'll close this issue as it's a duplicate. Sorry I haven't had the time to delve into #117 deeper yet.
Thanks!
