### ISSUE TITLE
Raw image data instead of image

### ISSUE THREAD

**Issue by Libig** [noelboss/featherlight#125]
I am trying to use gallery feature.
My images are not available directly, but each one has its own link, which returns image.
Link is (example): http://example.com/gallery/29, where 29 is the ID of images and is correclty returned by browser.

Returned header is:
HTTP/1.1 200 OK
Date: Wed, 25 Mar 2015 20:06:23 GMT
Server: Apache/2.2.22 (Win64) mod_ssl/2.2.22 OpenSSL/1.0.1c PHP/5.4.3
X-Powered-By: Nette Framework
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
Vary: X-Requested-With
Set-Cookie: PHPSESSID=aeet11s42mek9k8cis4cjfpcd7; path=/; httponly
nette-browser=3wz3j8c6ls; path=/; httponly
Keep-Alive: timeout=5, max=85
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: image/jpeg

Init of featherlight:
```html
<script type="text/javascript">
    $(document).ready(function(){
    $('a.gallery').featherlightGallery({
    gallery: {
        previous: '«',
        next: '»',
        fadeIn: 500
    },
    openSpeed: 500
});
    });
</script> 
```

Image placement in HTML code:
```html
<div id="gallery-wrapper">
    <a href="/gallery/29" class="gallery"><img src="/gallery/29/preview" alt="#1"></a>
</div>
```
However in the modal I don't see image but its raw source (just a bit of it belows):

����JFIF��;CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), quality = 85 ��C !"$"$��C��"�� ���}!1AQa"q2���#B��R��$3br�

What is wrong?

**Comment by Libig** [comment]
Did a bit of documentation reading and found type: 'image' option. Applied and now it works.

**Comment by marcandre** [comment]
Exactly :+1:
