### ISSUE TITLE
.webm and .mp4 support?

### ISSUE THREAD

**Issue by rwhol** [noelboss/featherlight#128]
Are there any plans for .webm and .mp4 support?
What I would like is for featherlight to detect and display these filetypes like it already does for images.
//rhwol

**Comment by marcandre** [comment]
No plans per say. Should at least be a plugin. Wanna write a PR?

**Comment by noelboss** [comment]
How about outsourcing detectors etc. as plugins or simple wiki examples how to implement? Because this is what FL is all about, barebones but extensible...

**Comment by marcandre** [comment]
Closing this, until there's a PR or more interest
