### ISSUE TITLE
Move opacity from .featherlight:last-of-type to something else

### ISSUE THREAD

**Issue by edu2004eu** [noelboss/featherlight#129]
Sometimes we have widgets that run after featherlight and insert divs right before the closing `</body>` tag, which makes this CSS rule to fail:

```.featherlight:last-of-type {
  background: rgba(0,0,0,.8);
}```

Steps to reproduce:
1. Initialize / show a modal using featherlight
2. Manually or programatically add any `div` before `</body>`
3. Notice that the grey background is gone, and it's all transparent now.

**Comment by marcandre** [comment]
A solution for this is to have a dedicated root.
Insert `<div class="featherlight-home">` towards the end of your body, and change the `root` option to `".featherlight-home"`. You might have to bump the `z-index` of that `<div>`, but probably not, I can't recall.
Does that work for you?

**Comment by edu2004eu** [comment]
What I did for right now was to remove `:last-of-type`, because I won't have any modals on top of each other (I'm guessing that's why the selector looks like that).

**Comment by marcandre** [comment]
Yes, it's for nested dialogs.
I'll close the issue then, which could be reopened if the solution I'm pointing to doesn't work.
Thanks

**Comment by robov** [comment]
Thanks... removing hte :last-of-type and boosting the z-index worked brilliant for me

**Comment by gmariani** [comment]
This still seems to be an issue. Just ran into this today in the Modern Events Calendar Lite (v5.7.5) plugin for WordPress. It has version 1.7.14 included to open up modals. I have a Firefox extension (Facebook Container) that was adding a node at the very end making the background color disappear due to last-of-type.
