### ISSUE TITLE
Show external URLs

### ISSUE THREAD

**Issue by SLQ-CommWeb** [noelboss/featherlight#132]
Sorry if I seem a bit daft here, just came across your plugin and it looks neat and small. I just can't get it to work on external URLs - is this possible to do?

In your example files, the AJAX URL is internal.

**Comment by marcandre** [comment]
`featherlight` uses `$.ajax` (more precisely `$.fn.load`), so if that works, `featherlight` will work.

You have to be careful about the "same origin policy" though. See [here](http://stackoverflow.com/questions/3076414/ways-to-circumvent-the-same-origin-policy) for example.
