### ISSUE TITLE
Background dissappeared when closing on div

### ISSUE THREAD

**Issue by robov** [noelboss/featherlight#133]
I want the lightbox (brilliantly created by the way) to show on page load
For this I use the following code.
Below teh js call there is a div box, when that is there, the background is no longer colored... how can I fix that ?
It is part of my wordpress plugin

PAGE:
....            
[script type="text/javascript"]
            $.featherlight($('#fl1'), {});
[/script]

        [div]sdfsd fds fds[/div]     
	[/body]
[/html]

**Comment by marcandre** [comment]
The lightbox must be last of it's type inside it's root.
Your call to `featherlight` should be after the last `<div>`, or else you'll need to provide `featherlight` its own `root`, see #129.
