### ISSUE TITLE
Remove title attribute from CSS <link>

### ISSUE THREAD

**Issue by ovinophile** [noelboss/featherlight#134]
I'd like to recommend removing the title attribute from the CSS link under Installation instructions. Not only does it cause "Featherlight Styles" to appear under the View > Page Styles menu in Firefox, but multiple links with different titles will cause some to not render.

More info: [http://stackoverflow.com/q/1959959](http://stackoverflow.com/q/1959959)

**Comment by noelboss** [comment]
I will fix this...

**Comment by marcandre** [comment]
Indeed. Fixed. Thanks for reporting this.
