### ISSUE TITLE
Opening and closing WMV video

### ISSUE THREAD

**Issue by asifkabani** [noelboss/featherlight#135]
I am using the hidden div method to open a wmv file in featherlight. This is what the wmv code has:

object width="600" height="338" id="MediaPlayer" classid="CLSID:22D6F312-B0F6-11D0-94AB-0080C74C7E95" 
    param name="FileName" value="myvideo.wmv" 
    param name="AutoStart" value="0"
    param name="ShowStatusBar" value="False" 
    embed pluginspage="http://www.microsoft.com/Windows/MediaPlayer/" type="application/x-mplayer2" showstatusbar="true"
/object

I have set the div of that to display none. When the featherlight opens up with the video embedded, I want it to then autoplay. Also if the user clicks the X or clicks off to close the featherlight then stop the video as well. Any idea on how I can achieve this? Sorry I'm not sure how to show code on github.

**Comment by marcandre** [comment]
Please read the info in the first part "Questions?" [here](https://github.com/noelboss/featherlight/blob/master/CONTRIBUTING.md#questions)
