### ISSUE TITLE
Removing <body> class by click on featherlight-close

### ISSUE THREAD

**Issue by iCr** [noelboss/featherlight#136]
Hi, i try to use this code for removing class from body (to prevent body scrolling), by clicking on featherlight close button:

$('featherlight-close-icon').on('click', function(){
    $('body').removeClass('modal-open');
});

But it have no effect. How to fix this?

**Comment by slavanga** [comment]
Looks like you just forgot the dot in front of the featherlight-close-icon selector.
This code should work:

```js
$('.featherlight-close-icon').on('click', function() {
    $('body').removeClass('modal-open');
});
```

**Comment by noelboss** [comment]
Solved?

**Comment by iCr** [comment]
Got this working using that method:
```
jQuery(document).on('click','.featherlight-close-icon',function(){
    jQuery('.featherlight').click();
	$('body').toggleClass('modal-open'); 
});
```
