### ISSUE TITLE
Default Loader CSS?

### ISSUE THREAD

**Issue by robneu** [noelboss/featherlight#137]
I've recently made a [WordPress plugin](https://wordpress.org/plugins/wp-featherlight/) to wrap featherlight and one of the things I needed to add was a loader for slower-loading images. I was able to do it without changing anything in the script so I was wondering if you'd like to implement the CSS I'm using as part of the defaults.

You can see the new code [here](https://github.com/wpsitecare/wp-featherlight/blob/develop/css/wp-featherlight.css#L1-L30) and [here](https://github.com/wpsitecare/wp-featherlight/blob/develop/css/wp-featherlight.css#L126-L149). If you're interested in making this part of the default, I'd be happy to send a PR.

**Comment by noelboss** [comment]
Great! I would make this a plugin tough, like gallery... Or simply ad Wiki entry, this is nice to have, but Featherlight is about minimalist :)

**Comment by robneu** [comment]
I think a Wiki entry probably sounds like the best way to go. I'll get the CSS added to a new wiki page with some screenshots tomorrow. :+1:

**Comment by noelboss** [comment]
Awesome!
