### ISSUE TITLE
Change he to he or she's doing

### ISSUE THREAD

**Issue by itzaks** [noelboss/featherlight#138]
From the demo site:
"It's for the pro who knows what he’s doing and just needs a barebones plugin."

We should embrace women in this man-heavy culture, and not exclude them :)

**Comment by marcandre** [comment]
:+1: good comment, thanks.

**Comment by noelboss** [comment]
I'm all for equal rights for women and men, but this is not the place where I want this discussion to take place. When I use he, you can be sure it's without preference above she, I just wrote how it came to mind. So whenever you encounter he, she's included, when you encounter she, he is included. Women and men are equally precious, so he and she are interchangeable, thus, he = she. Thus this is no issue.

I don't want this topic to surface on this repo again. Thanks for your respect.

**Comment by itzaks** [comment]
Yes I'm sure you are :) But when my girlfriend read it she reacted on the word because it wasn't including her, thus we felt it was an issue. I didn't mean it needed to be changed solely to "she's" but rather include both sexes. Anyway, if you don't feel like changing I respect that.

**Comment by noelboss** [comment]
Hey Itzaks, I'm happy to hear that you read it with your girlfriend and I can assure both of you, she is more than included in that "he" :)
Please tell your girlfriend a personal and warm hello from me and that I'm glad that we live in a world, where women as she are responsible for a great part of the empathy and peace we experience in everyday life. I also thank you for your bold feedback and your respect.

**Comment by blasut** [comment]
Hi,

@noelboss if the word he is including she why can't it be the other way around?

Why can't she be the word in the readme?
