### ISSUE TITLE
Demo page JS error "j.open is not a function"

### ISSUE THREAD

**Issue by creativejuiz** [noelboss/featherlight#140]
Hi there,

I actually have this error on the demo page:
http://inft.ly/vRaRKQg

I browse on Firefox for Mac OSX in all the latest versions :)
Thank you and good luck.

**Comment by robneu** [comment]
+1 on this. Looks like it's related to the `1.3.0` release somehow.

**Comment by marcandre** [comment]
Oups, embarrassing.
Fixed, although I don't get how come tests passed. I'll keep that opened until I fix the tests.
Thanks for the complete report!

**Comment by marcandre** [comment]
Oh, I guess it needed a test where the fixture had a `data-featherlight="something"`, was unlucky there wasn't.

**Comment by creativejuiz** [comment]
Ah ah :)
Thank you for your work ;)
