### ISSUE TITLE
Transparent background disappears

### ISSUE THREAD

**Issue by manelgarcia** [noelboss/featherlight#141]
Hi!

First things first, congratulations for featherlight, great minimal piece of code. Just having one issue.
As english is not my native lang, I thought than a video would be better to explain the issue.

Basically, when I switch the browser for any other app and get back to the browser (with a modal opened) then the background magically disappears.

Video link: https://www.youtube.com/watch?v=eDzST_n0g5o

Thanks a lot.

**Comment by marcandre** [comment]
You certainly have code that does something on focus lost or something, and appends a `<div>` to your `<body>`. Featherlight must be the last in the `root` (by default `<body>`), so you'll have to provide featherlight a dedicated root and specify it in your options.
HTH
