### ISSUE TITLE
How does one retrieve `current` and `total` slide numbers?

### ISSUE THREAD

**Issue by alancwoo** [noelboss/featherlight#143]
I've scanned the returned object from `current()` but for the life of me cannot figure out how to retrieve the `current` and `total` slide numbers? (So I can update a div with a counter like `x of y`).

I've been able to find the total slides, though not exactly ideal, through `$.featherlight.current().$source.length` *I say not exactly ideal because I believe this may vary depending on the HTML upon which featherlight is instantiated, for my own use I had to traverse the source to the appropriate level before counting*

**Comment by marcandre** [comment]
I will be grateful if you could follow our [preferred way to ask questions](https://github.com/noelboss/featherlight#questions) and will be glad to answer there.

You can also check out the source of the `navigateTo` method

**Comment by alancwoo** [comment]
Ah I'm sorry about that. Post is on SO: http://stackoverflow.com/questions/30744571/how-to-get-current-slide-and-total-slides-in-featherlight-lightbox

**Comment by marcandre** [comment]
Thanks, much appreciated.
