### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by framerate** [noelboss/featherlight#145]
Since this app is designed to be developer friendly, could we get it published officially to NPM? In my experience people seem to be moving towards `npm` for front end stuff quite often and using stuff like `babeljs` to develop modularly. 

Thanks! Love the library!

**Comment by tunnckoCore** [comment]
:+1: didn't notice that when found it today.

**Comment by pguth** [comment]
:+1:

**Comment by marcandre** [comment]
Anyone can provide a PR?

**Comment by marcandre** [comment]
Or @noelboss ?

**Comment by mikelambert** [comment]
It seems you already have a package.json (though I would argue that "main" should point at src/featherlight.js instead).

Regardless, it should be as simple as this to add an NPM package:
https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by arthurio** [comment]
@noelboss Would you mind publishing the last release to npm? @mikelambert the last release contains the change you mentioned.

**Comment by Jaans** [comment]
Is to fix the issue with NPM package pointing to the gruntfile.js instead of the featherlight.min.js file?

**Comment by Jaans** [comment]
From the GitHub history, this is indeed the fix for the incorrect value for main in packages.json.

Can this please be released to npm? This issue fundamentally breaks JSPM's ability to consume the NPM package.

Thanks!

**Comment by marcandre** [comment]
Sorry, I thought I had. Should be done now.

**Comment by Jaans** [comment]
Brilliant! Thank you very much! It works now. 

FYI: For those who use jspm, you can reference is with "jspm install npm:featherlight"
