### ISSUE TITLE
if "Swipe" no "Next & Previous" in gallery

### ISSUE THREAD

**Issue by OriginalDinao** [noelboss/featherlight#148]
Silly little issue that had me searching in all the wrong places -_-U , in featherlight.gallery.js "if (swipeAwareConstructor) ..." doesn't createNavigation.  

Quick fix, copy paste of "else" into "if".

Not sure if they are intended to be mutually exclusive but was very confusing for me, nobody else had this?
Love it still ^_^

**Comment by marcandre** [comment]
Indeed, this is what is intended. For touch devices, there is no mouseover...

**Comment by OriginalDinao** [comment]
My apologies, something unique in Chrome on Desktop (works everywhere else) is triggering the swipe ability while emulation is off.  I'll try to isolate the problem, and let you know if I ever figure it out.

**Comment by graceWeareduo** [comment]
I know this issue is closed, but was wondering if there is a way to enable the next/prev buttons for touch devices?

**Comment by marcandre** [comment]
No easy way, no.

A good PR with a new option for that could be accepted though.

**Comment by OriginalDinao** [comment]
Edit file "featherlight.gallery.js":

around line 55:
55:    if (swipeAwareConstructor) {
56-8:    'self._swiper....;'
            PASTE here
59:    } else {
60-2:     'self.$instance.....;' <-COPY these lines
63:    }

Minify JS again and done :)

**Comment by marcandre** [comment]
Or remove the `else {` and closing `}`

**Comment by graceWeareduo** [comment]
I've tried removing 

else {
self.$instance.find('.'+self.namespace+'-content')
.append(self.createNavigation('previous'))
.append(self.createNavigation('next'));
}

But doesn't seem to make any difference?

**Comment by marcandre** [comment]
I often talk too precisely. Remove the `else {` and closing `}`, but don't remove what's in between. If you read it, it should be quite obvious why not...

**Comment by graceWeareduo** [comment]
That did the trick, thanks very much for your help :)

**Comment by wstoettinger** [comment]
@OriginalDinao did you find out what was causing the problem in chrome dekstop? i've run into the same problem.

**Comment by james-h-stephens** [comment]
@wstoettinger Sorry for the late reply. I just ran into the same issue myself.  If your machine has a touch screen, Chrome sets itself as a touch screen. You can disable that by following the instructions [here](http://ccm.net/faq/40811-google-chrome-how-to-disable-touch-input).
