### ISSUE TITLE
Persist issue

### ISSUE THREAD

**Issue by twinsit** [noelboss/featherlight#149]
I am trying to use the persist function, because otherwise I have problems with my javascript.
The strange thing is that when I use persist, like this:   $.featherlight($("#addproperty"), {persist:"true"});
the first window opens like it should be, the second one is just an empty box.

Is there something I do wrong? Thanks!

**Comment by marcandre** [comment]
Is it possible to get an example in jsfiddle or similar?

**Comment by marcandre** [comment]
Closing until we get a reproducible example.

**Comment by jfeust** [comment]
@marcandre. We're also getting this issue when trying to use persist with on-page content.

Here's a [jsfiddle](https://jsfiddle.net/syj9s5wb/1/) that recreates it.

**Comment by marcandre** [comment]
Thanks for the example, @jfeust 
The `persist` is meant for featherlight bound to an action, at least for now. See [this modified example](https://jsfiddle.net/3gq87uLw/) which works, for example.

There's been requests so it places the elements back where it found them, in which case your example would work.
