### ISSUE TITLE
Ability to reorder or add/remove slides dynamically?

### ISSUE THREAD

**Issue by kevinberonilla** [noelboss/featherlight#153]
I'm building an application with a gallery utilizing the plugin and its gallery extension, but entries can be sorted and filtered dynamically. Is there a way to destroy the plugin's established settings? I found that reinitializing the plugin after DOM changes does not help (deleting slides and reinitializing result in blank content for that deleted slide instead of skipping the entry entirely).

**Comment by kevinberonilla** [comment]
I found a workaround that involves using the .stop() function on the selector I've initialized the plugin with. If you have a better/more appropriate way, please let me know. Otherwise, I supposed you can close this issue.

**Comment by echolevel** [comment]
I'm very interested in this too - I've got an infinite scrolling script adding content elements to my grid of featherlightable thumbnails, and while reinitialising featherlight gallery from the console appears to add the new items, the next/prev loop remains as it was when the gallery was first initialised - no new slides added.

@kevinberonilla - I'm curious to hear about your .stop() workaround, if you wouldn't mind sharing it...? At this point, I don't care how inappropriate it might be :)

Cheers

**Comment by marcandre** [comment]
Are you (both) using the `filter` option?

 If not, there's no way FL can "magically" extend the set of images; you started from a set of images, and you bound FL on it, there's no jQuery API to refresh that set. There could be an API to do a rebinding though

I believe that you don't use the `filter` option, but if you do, then FL's `slides` method will "refresh" the slides constantly.

E.g:
    $('.my-gallery').featherlight({filter: '.a-slide'})
This is bound on `.my-gallery` (which should remain constant) and will do ` $('.my-gallery').find('.a-slide')` everytime it's needed.

**Comment by echolevel** [comment]
Hi @marcandre - I tried that, and variations thereof, but all that happens is the next/prev loop is reduced to 1 (ie next/prev just repeatedly show the same slide).

This is how my dynamically duplicated grid item looks:

```
<div class="col-xs-12 col-sm-4 col-md-4 tblitem">
   <section data-featherlight-gallery data-featherlight-filter="a" >
      <a href="#" id="{Permalink}"  class="gallery" data-featherlight="#fb{PostID}">

      [...]

      <div class="lightbox" id="fb{PostID}">
      [...]
      </div>
   </div>
```

**Comment by marcandre** [comment]
If you could provide a jsfiddle, that would be a big time saver.

**Comment by echolevel** [comment]
Forgive me: now that I've rearranged my tangled rats' nest of a template, it's successfully adding new content to the gallery loop. Thanks for clarifying the filter option for me!

**Comment by marcandre** [comment]
Great :-) 
I'm closing this, if anyone runs into problems, let me know and I'll reopen.
