### ISSUE TITLE
Is there a way to unbind featherlight?

### ISSUE THREAD

**Issue by MickeyKay** [noelboss/featherlight#154]
I have a unique situation in which download links are hooked up to pop up a featherlight window with a verification form, which when completed closes the featherlight modal. Once this is done, clicking a download link should no longer trigger featherlight, but should go directly to the download. All of these needs to happen without a refresh. Any way to unbind featherlight once it's already been set?

**Comment by noelboss** [comment]
Use the beforeOpen function to check if a variable or cookie has been set with the registration form and then prevent featherlight to open, instead trigger the download.
```
    /* Called before open. can return false to prevent opening of lightbox. Gets event as parameter, this contains all data */
    beforeOpen:   $.noop,                
```

**Comment by MickeyKay** [comment]
Awesome. Thanks!
