### ISSUE TITLE
Featherlight with TinyMCE 

### ISSUE THREAD

**Issue by draconusdesigns** [noelboss/featherlight#155]
I have a tinyMCE init that applies to all textareas on my site with the class of wysiwyg. They work perfectly everywhere on the site, with the exception of in featherlight modals. In the modals, the tinyMCE shows up properly, but you cannot edit the field or click any of the buttons.

Any ideas on how I can fix this issue?

**Comment by MickeyKay** [comment]
Have you tried re-initing the TinyMCE when the lightbox is triggered?

**Comment by draconusdesigns** [comment]
Holy cow that did it. 

Thanks, 
Ryan Holt
Web Developer
Draconus Designs
ryan@draconusdesigns.com

**Comment by MickeyKay** [comment]
Badabing, badaboom! Happy that helped :) I have to admit, secondary/delayed
initing has been the most significant, ongoing issue for me with all things
JS :)

**Comment by draconusdesigns** [comment]
Is there a way to make the modals not be clones? That seems like it would solve these sorts of issues. 

Thanks, 
Ryan Holt
Web Developer
Draconus Designs
ryan@draconusdesigns.com

**Comment by draconusdesigns** [comment]
And by the way, I love featherlight. It is my go to for every project now that needs such a thing. Thanks for all the hard work making it great.

Thanks, 
Ryan Holt
Web Developer
Draconus Designs
ryan@draconusdesigns.com

**Comment by marcandre** [comment]
> And by the way, I love featherlight.

Glad you do :smile:

> Is there a way to make the modals not be clones?

https://github.com/noelboss/featherlight#questions
