### ISSUE TITLE
Using featherlight with spin.js

### ISSUE THREAD

**Issue by carlospence** [noelboss/featherlight#156]
In this function $.featherlight.prototype.loading, I used an image directly like this
$.featherlight.prototype.loading = "<img src="/Areas/Admin/Content/Images/ajax-loader.gif" class="spinner">";

But I want to use spin.js for the spinner loading so i passed a function into the loading configuration property of featherlight like this

$.featherlight.prototype.loading = function () {
    var opts = {
        lines: 12 // The number of lines to draw
, length: 28 // The length of each line
, width: 14 // The line thickness
, radius: 42 // The radius of the inner circle
, scale: 1 // Scales overall size of the spinner
, corners: 1 // Corner roundness (0..1)
, color: '#000' // #rgb or #rrggbb or array of colors
, opacity: 0.25 // Opacity of the lines
, rotate: 0 // The rotation offset
, direction: 1 // 1: clockwise, -1: counterclockwise
, speed: 1 // Rounds per second
, trail: 60 // Afterglow percentage
, fps: 20 // Frames per second when using setTimeout() as a fallback for CSS
, zIndex: 2e9 // The z-index (defaults to 2000000000)
, className: 'spinner' // The CSS class to assign to the spinner
, top: '50%' // Top position relative to parent
, left: '50%' // Left position relative to parent
, shadow: false // Whether to render a shadow
, hwaccel: false // Whether to use hardware acceleration
, position: 'absolute' // Element positioning
    }
    var target = $("#loading"); //document.getElementById('loading');
    var spinner = new Spinner(opts).spin(target);
    $("#loading").show();
}

But its not working. How can I used spin.js with Featherlight 
Thanks

**Comment by marcandre** [comment]
Please check the [section on questions](https://github.com/noelboss/featherlight#questions)
