### ISSUE TITLE
Close icon CSS needs font-family Arial, not font Arial

### ISSUE THREAD

**Issue by revelt** [noelboss/featherlight#158]
gentlemen,
Currently we have:
````
.featherlight .featherlight-close-icon {
...
font: Arial, sans-serif;
...
}
````

let's set it to font-family:
````
.featherlight .featherlight-close-icon {
...
font-family: Arial, sans-serif;
...
}
````

If it's not font-family, Chrome Inspect ignores it, reports "Invalid property value" and shows icon with a plane. When I change it to `font-family`, all is fine.
<img width="388" alt="font-family" src="https://cloud.githubusercontent.com/assets/8344688/9078761/a434f322-3b3a-11e5-84dc-66b462bbb88a.png">
<img width="405" alt="font-only" src="https://cloud.githubusercontent.com/assets/8344688/9078762/a44e3d64-3b3a-11e5-980a-a49710eb2997.png">

**Comment by marcandre** [comment]
Indeed, thanks!
