### ISSUE TITLE
I want vertical images to be big and scroll in featherlight.

### ISSUE THREAD

**Issue by tekfunk** [noelboss/featherlight#159]
I'm working on a portfolio page that includes screenshots of webpages and are very tall.  I would like the image to NOT scale down to try to fit it all.  How can I get a min-width going for these ones?

**Comment by robneu** [comment]
I think you'll have better luck asking this over on Stack Exchange. There's a [questions section](https://github.com/noelboss/featherlight#questions) in the readme with more info.

**Comment by marcandre** [comment]
:+1:, thanks @robneu
