### ISSUE TITLE
Apply featherlight to per JS loaded content

### ISSUE THREAD

**Issue by MartinMuzatko** [noelboss/featherlight#162]
I'm trying to dynamically load images (as a result of a post request)

after manually initializing featherlight (since featherlight isn't listening to dynamically loaded content)
I managed to get a featherlight frame with overlay, but the image within it is not displayed.

See reduced testcase: http://jsfiddle.net/ovvtr7Lc/2/

**Comment by MartinMuzatko** [comment]
Okay, featherlight seems to listen to dynamically added content! it works great now.
you should have noticed that in the documentation + that if you initialize a gallery, you don't need the featherlight data attribute PER image/a element.

I found that out when taking a look at the contribution fiddle: http://jsfiddle.net/JNsu6/15/

**Comment by marcandre** [comment]
Congrats on finding the `filter` option. PR on documentation welcome.
