### ISSUE TITLE
How to place element inside of .featherlight-inner instead of applying .featherlight-inner to 

### ISSUE THREAD

**Issue by MickeyKay** [noelboss/featherlight#164]
At present, if I have a featherlight-enabled, linked image like the following:
```
<a href="image.jpeg">
   <img src="image.jpeg" />
</a>
```

I end up with the following markup when the lightbox is triggered:
```
<img src="image.jpeg" class="featherlight-image featherlight-inner">
```

For a variety of reasons (adding a relatively positioned caption, customizing padding, etc), it would be very helpful to have something like the following markup instead:
```
<div class="featherlight-inner">
    <img src="image.jpeg" class="featherlight-image">
</div>
```

Is this possible? Is there a simple way to customize, and/or add, the content wrapper? Thanks!

**Comment by marcandre** [comment]
Many ways I can think of.

One:

    <a href="#img">
       <div id="img">
         <img src="image.jpeg" />
      </div>
    </a>

Two: modify the content filter 'image' to do what you want

Three: create a new content filter to do what you want
 
Four: Do whatever restructuring you want in an `afterContent` callback.

In the future, please ask questions on StackOverflow as requested in the readme.
