### ISSUE TITLE
DOM loading doesn't work on mobile?

### ISSUE THREAD

**Issue by Timvst** [noelboss/featherlight#170]
Hello,

In de following project http://download.omroep.nl/nos/nosop3/020915_vluchtelingenkaart/pub/map.html featherlight is called to load DOM content when an SVG element is clicked/touched. But when I test on mobile devices (iOS and Android), the lightbox appears and disappears immediately. What am I missing here?

Kind regards,

Tim

**Comment by marcandre** [comment]
Sure it does, as you can verify by looking at the demo, or issuing a `$.featherlight('<b>Hello</b>')` command in the iOS Simulator console.

Error lies in your code, of course start looking at anything touch-only related. I think the `$.featherlight($('url'), {})` is wrong.
