### ISSUE TITLE
Ajax is not working inside Featherlight

### ISSUE THREAD

**Issue by nicefellow1234** [noelboss/featherlight#172]
I am trying to add ajax photo uploading script inside a Featherlight lightbox but it's not working! So if anyone could please let me know what I am doing wrong, that'd be great! I am already adding JQuery library; everything else is working fine but ajax is not submitting the uploaded photo when the uploading form is kept in lightbox div in order to load it in a lightbox!

**Comment by marcandre** [comment]
Glad [you asked on StackOverflow](http://stackoverflow.com/questions/32531876/ajax-is-not-working-inside-featherlight), although you didn't make a simplified working example say in a fiddle.

**Comment by nicefellow1234** [comment]
Sure...let me give you access to my live project...Where I have this issue : 
Login in there and then open clients management tab page and there will be a button as "Add New Profile" where I have put the php ajax image uploading form in that lightbox and it doesn't work..! 
Site Link : http://huntedhunter.com/drag_gallery/
Login Access Details : 
Username : Admin
Password : umair1111
More like the the ajax upload form doesn't work but when I click submit button manually then it works and submit form and the image is uploaded but doesn't show in there which is also related to ajax success triggers and get back html from php upload but it doesn't put that success in there..!
