### ISSUE TITLE
CloseOnEsc not working when using custom closeTrigger (for example 'mousedown')

### ISSUE THREAD

**Issue by zmrd** [noelboss/featherlight#178]
Close on escape keyup not working because of click() trigger (see code bellow) 

onKeyUp: function(_super, event){
                if(27 === event.keyCode) {
                    if (this.closeOnEsc) {
                        /* this.$instance.find('.'+this.namespace+'-close:first').click(); //original faulty code
                          this.$instance.find('.'+this.namespace+'-close:first').trigger(this.closeTrigger); //one possible way, but this.close() is better i think */
                        this.close();
                    }
                    return false;
                } else {
                    return _super(event);
                }
            },

**Comment by marcandre** [comment]
Agreed, and agree with the `close()` fix too :-)

You are pretty close from an actual pull request...

**Comment by marcandre** [comment]
Fixed in 2.3.5.
Thanks for raising the issue.
