### ISSUE TITLE
how to override css

### ISSUE THREAD

**Issue by heaversm** [noelboss/featherlight#179]
Hi - maybe I'm not understanding the concept of the variant, but if I pass a variant with my class, say `.myclass` and then include the default css for featherlight, then my own css, I can't override things without an `!important` statement, or without matching the media query to the css plus overriding the `:last-of-type, :first-of-type` stuff, which I don't want to do.

For example, featherlight's rule for the background color is:

```
@media all
.featherlight {
  background: rgba(0,0,0.8);
}
```

and my desired CSS is

```
.myvariant {
  background: green;
}
```

Is there an easier way to get this working?

**Comment by marcandre** [comment]
AFAIK, media query do not add any specificity, so both rules you wrote have the same weight. If your variant comes after, if should override the previous one.

You could consider using `.featherlight.myvariant` if you don't want to care about ordering?

**Comment by tandemloop** [comment]
How do we tell featherlight to use certain css class for the design/background?
