### ISSUE TITLE
Checkboxes inside FeatherLight

### ISSUE THREAD

**Issue by matchboxhero** [noelboss/featherlight#180]
Hi,

I have discovered a problem with featherlight and clicking a label to select a checkbox, please see the this pen for a demo;

http://codepen.io/matchboxhero/pen/KdQdjK

You should be able to click the label inside of the lightbox to select the checkbox.

Thanks.

**Comment by marcandre** [comment]
Unless you set `persist` option, you'll have two objects with same ID.

**Comment by marcandre** [comment]
PS: Thanks for the codepen, much appreciated!

**Comment by matchboxhero** [comment]
Great, thanks @marcandre that did the trick :)
