### ISSUE TITLE
beforeClose doesn't seem to receive an argument

### ISSUE THREAD

**Issue by drywall** [noelboss/featherlight#181]
Documentation suggests that the beforeClose callback receives the event as a parameter, but it seems to always be undefined in my callback.

I can see on line 278 that the close function expects an event. But nowhere does close() get called with an argument. Line 156, 476... neither passes anything to close() method.

**Comment by drywall** [comment]
The fix to line 156 is easy, since event is defined. Not sure about line 476 — maybe I'm looking at the public method in which case event should be null, perhaps?

**Comment by marcandre** [comment]
Indeed. Fixed for all three cases (closebox, escape and global method). Of course, if you don't pass anything to the global method, you won't receive anything.
Thanks for raising this issue!
