### ISSUE TITLE
Calling .(val) inside Featherlight

### ISSUE THREAD

**Issue by jeroenpol** [noelboss/featherlight#182]
Hello!

I got a form inside Featherlight. When you click the 'saveButton' i want to be able to acces all the attributes in the form inside my jQuery function. But i just can't seem to get the updated (filled in) values.

My HTML:

    	<div class="lightbox" id="eventSettings">
		<form action="" method="post" id="createNewEvent" class="newEvent">
			<h1>Create new event</h1>
			<label>
				<span>Company:</span>
				<input id="company" type="text" name="company" value="Company Name" readonly />
			</label>

			<label>
				<span>Project:</span>
				<select id="project123" name="project">
					<option value="1">Option 1</option>
					<option value="2">Option 2</option>
				</select>
			</label> 

			<label>
				<span>What did you do:</span>
				<input id="whatdidyoudo" type="text" name="whatdidyoudo" />
			</label>

			<center><button type="button" id="saveButton">Save</button></center>

		</form>
	</div>

My javascript:

    $('#saveButton').click(function() {
    test = $('#whatdidyoudo').val();
    console.log(test);
    });

**Comment by niladam** [comment]
I think you'd better use 

```javascript
$("body").on( "click", "#saveButton", function() {
	test = $('#whatdidyoudo').val();
	console.log(test);
});
```

Since featherlight doesn't exist upon your 1st load (that actually loads the script).

**Comment by jeroenpol** [comment]
It still gives me undefined, so it doesn't give me the updated value

**Comment by niladam** [comment]
Well, this isn't actually a featherlight issue. It's more of a script issue (your script) and without actually seeing your code i'm unable to provide you with a solution.

**Comment by jeroenpol** [comment]
You can download my site here:

https://www.dropbox.com/sh/k9ot2r82o9d9671/AAC0fyEYcFdDevY6FYvyCnCua?dl=0

**Comment by niladam** [comment]
For your specific needs try this:

```javascript
$("body").on( "click", "#saveButton", function() {
	test = $('.featherlight select#project option:selected').val();
	console.log("Hello " + test);
});
```

**Comment by jeroenpol** [comment]
Thanks a lot! :+1: It worked

**Comment by niladam** [comment]
No problem :)
