### ISSUE TITLE
beforeOpen goes infinite

### ISSUE THREAD

**Issue by marauxus** [noelboss/featherlight#185]
Overriding the default beforeOpen behavior causes an infinite loop, even if the function just says return false:

https://jsfiddle.net/7bwnf84x/5/

**Comment by marcandre** [comment]
lol, the only way to reproduce this bug is to (1) use the auto bind feature *and* (2) have a `beforeOpen` returning `false`. Cute find :smile_cat: 

Fixed in 1.3.5

**Comment by marcandre** [comment]
PS: Thanks for the fiddle, much appreciated, even for a simple example like this!
