### ISSUE TITLE
Create gallery from images elements only

### ISSUE THREAD

**Issue by katrinkerber** [noelboss/featherlight#190]
I'd like to create a gallery from a list of images that aren't wrapped around anchors:

````
<img src="image1.jpg" data-featherlight-gallery>
<img src="image2.jpg" data-featherlight-gallery>
<img src="image3.jpg" data-featherlight-gallery>
````

Clicking the images results in the `Featherlight: no content filter found` error.

I've tried all kinds of things with manual method calls etc, but I am not able to figure this out and have a feeling it's something simple I am overlooking.

What can I do to get this gallery working?

**Comment by phrix32** [comment]
Hi! Does v1.0 or the workaround for older versions, described in issue #88 , resolve your problem?

**Comment by marcandre** [comment]
One way is to use `data-featherlight-gallery-target-attr="src"`, otherwise it will look for `href`.

For any other questions, please use StackOverflow.
