### ISSUE TITLE
No padding on images

### ISSUE THREAD

**Issue by bondimedical3** [noelboss/featherlight#193]
![feather](https://cloud.githubusercontent.com/assets/10808588/11972202/096b6818-a99d-11e5-8ef2-a151e34b66f8.png)
I am finding that the padding on the bottom of images is missing but if I remove the border then it appears?
http://patricksquared.com/cc6/electronics/meelectronics-air-fi.html

**Comment by marcandre** [comment]
Since our examples work fine, I'd have to ask you do dig a bit deeper as to why that is...

**Comment by bondimedical3** [comment]
I am new to featherlight. Where can I see your examples?

**Comment by bondimedical3** [comment]
Okay, I have copied what you have done and simply removed the border and made the background black. I now have padding however I have noticed another issue. On mobile devices I am getting a horizontal scroll bar?

**Comment by bondimedical3** [comment]
I managed to get rid of the scroll bars in the images by setting overflow: hidden; in .featherlight .featherlight-content and putting a padding around the image in .featherlight .featherlight-image
