### ISSUE TITLE
Question: Modifying elements in "active" lightbox?

### ISSUE THREAD

**Issue by DJWLJR** [noelboss/featherlight#194]
I am using Featherlight to display an HTML form. Updates to the form field values are triggered by other page events using jQuery (event listeners, etc,) which then manually trigger the Featherlight display. This works fine if the lightbox display is not already active.

While attempting to add a button to the form to clear/reset the values, I discovered that changes made via functions and event listeners to the field values are not reflected in the active Featherlight display (at least not until it is *re-opened*.) The form works as expected otherwise, and submits with the correct values, but the fact that I could not update the displayed value while *active* was frustrating.

It behaves as if Featherlight is displaying a "copy" of the object passed and then updating the original. **Is that correct? Is there an easy way update the the lightbox while it is still open?**

**Comment by marcandre** [comment]
Please check the doc on `persist`, I think this is what you're looking for. If not, or for any question, please post on StackOverflow (like I wrote just about anywhere I could).
