### ISSUE TITLE
Lightbox content displayed "inline" on page as well as in the modal

### ISSUE THREAD

**Issue by bestdamnfriend** [noelboss/featherlight#196]
Using the following simple code:

`<a href="#" data-featherlight="#modal">open modal</a>`
`<div id="modal">hello world</div>`

I get the following on the page:

`open modal`
`hello world`

**And** the following in the modal:

`hello world`

I have no dependencies on the page except for jQuery 1.11.3

**Comment by josephbydeign** [comment]
I also have this problem

**Comment by marcandre** [comment]
`Featherlight` doesn't hide your content for you, so what you are describing is as per spec.

**Comment by josephbydeign** [comment]
Once I had finished yesterday I actually thought about it and realized that was so. @bestdamnfriend to do what you want include the content in another html file and call it with ajax. https://github.com/noelboss/featherlight#usage

**Comment by marcandre** [comment]
Or put it inside a `<div>` set to `display: none`.

**Comment by josephbydeign** [comment]
Sorry to come back to an old(ish) thread, but just wanted to clarify for future reference, adding `display:none;` inline to the element doesn't work but giving the element a class with the css display attribute set to none does works. The lower priority is needed for `display:none;` to be overridden by the lightbox.
