### ISSUE TITLE
gallery switch after custom style and iframe item

### ISSUE THREAD

**Issue by misace** [noelboss/featherlight#204]
In default no gallery plugin featherlight, when open lightbox(custom style & iframe), it'll add tag class on div with custom or featherlight-iframe.

when I use  gallery plugin, I found if put default custom iframe type lightbox item in the same gallery group, when switch to the custom one and back to default, it will cover to default style with add custom class on div, same does iframe add  featherlight-iframe.

featherlight-iframe class will set     
border-bottom: 0;
padding: 0;

it cause other text and img type item padding:0 after through iframe lightbox
If possiable switch different type lightbox item with gallery , change tag class in the same time?

**Comment by marcandre** [comment]
Sorry, I do not understand :-(

This looks like a question, but I'm not even sure. Please refer to https://github.com/noelboss/featherlight/blob/master/CONTRIBUTING.md for how to ask questions.

Thanks

**Comment by misace** [comment]
Sorry for this question explained not clearly enough.
I put code on [http://jsfiddle.net/tmaajhof/1/](url)

default style is white , custom style is black and iframe style  is no padding.
if first open is custom one, then all gallery item style will change to black,
same as iframe open first will make othe gallery item no padding.

**Comment by marcandre** [comment]
https://github.com/noelboss/featherlight/blob/master/CONTRIBUTING.md
