### ISSUE TITLE
Option to disable iterations in gallery

### ISSUE THREAD

**Issue by joostthehost** [noelboss/featherlight#205]
When opening a gallery, navigating beyond the last (or first) image causes the gallery to restart from the start (or end).
I'd like to propose an option to prevent this iterating behavior, thus hiding the navigation arrow to go to the next image if you've reached the end of the gallery.

Maybe a setting like the following?
`data-featherlight-iterate="false"`

**Comment by jakubzwierzynski** [comment]
+1 I would really like that option

**Comment by joostthehost** [comment]
@jakubzwierzynski Nice! Would you mind sharing your solution? :)

**Comment by jakubzwierzynski** [comment]
@joostthehost In /js/src/vendor/featherlight.gallery.js in callbackChain beforeContent:

`beforeContent: function() {
				var current = this.images().index(this.$currentTarget);
				var len = this.images().length;

				(current == len - 1) ? $('.featherlight-next').hide():$('.featherlight-next').show();
				(current == 0) ? $('.featherlight-previous').hide():$('.featherlight-previous').show();
			}`

**Comment by marcandre** [comment]
I'm thinking that adding a specific class for the "last" and the "first" button would be a good solution; it's then easy to hide the button via CSS, or disable it and dim it.

**Comment by jakubzwierzynski** [comment]
@marcandre Sure, it could be done in the above example as well

**Comment by marcandre** [comment]
You now have `featherlight-first-slide` and `featherlight-last-slide` classes added for you.

**Comment by robneu** [comment]
Unless I'm missing something, this seems really pointless to me. Can't you just use `last-of-type` or `last-child` selectors to do this if you need to? Why include more default code for it?

**Comment by jakubzwierzynski** [comment]
It's not for slides it's for navigation buttons to show/hide on first/last slide

**Comment by marcandre** [comment]
Yeah, the classes are turned off or on depending on which slide is currently showing.

**Comment by robneu** [comment]
Ah, I see what it's doing now now. :+1: Sorry for the confusion.
