### ISSUE TITLE
popup background gets lost with multiple instances

### ISSUE THREAD

**Issue by fuxifex** [noelboss/featherlight#206]
when using eg. 2 instances of the plugin, only one instance will display the black ground, on the other one it's missing..
i'm using this command for opening: $.featherlight(div, me.options);

**Comment by marcandre** [comment]
Only the topmost featherlight has a visible background, that's per design.
So I don't understand your issue, not sur if bug report of question

**Comment by fuxifex** [comment]
i'm sorry .. i found out that it's intereferencing with the zebra datepicker plugin:
http://stefangabos.ro/jquery/zebra-datepicker/
i couldn't find out why ..

**Comment by marcandre** [comment]
Maybe you need to setup a `root` for featherlight, check the docs
