### ISSUE TITLE
Ability to display image or HTML depending on Content-Type of response

### ISSUE THREAD

**Issue by tjwood100** [noelboss/featherlight#207]
I have a website that displays photos submitted by the user.

When they upload a photo, I generate thumbnails immediately, but the generation of large versions of the photo happens asynchronously. So when I return a page of thumbnails, when the user clicks on a thumbnail I want them to be able to see the large image in a Featherlight box if it's ready, or a "sorry, try later" message in the box if it's not.

I have a script on the server that is loaded like /viewimage?i=123.

Initially I tried having that script return either the real image or a different image (with the "sorry" text encoded in that image), and setting data-featherlight-type to image, but then the result seems to be cached and won't be reloaded if the user clicks the thumbnail again.

So I tried having the viewimage script instead return either `<p>Sorry...</p>` or `<img src="realimg.jpg">` and set data-featherlight-type to ajax. That does basically what I want except that the image is now shown full size and isn't scaled in the Featherlight box to fit the browser window.

Is there a better way? 

To me it would make sense if Featherlight could tell the content type from the header returned by my script, either text/html or image/jpeg, and display accordingly, rather than having to specify it upfront. Would that be easy to implement? Or is there another way that I'm missing?

**Comment by marcandre** [comment]
Seems like an interesting problem, but I don't have time to help you out.
I don't see how we can modify featherlight easily.
Please ask this as a StackOverflow question.
Good luck.
