### ISSUE TITLE
multiple instances problem

### ISSUE THREAD

**Issue by nicostem** [noelboss/featherlight#208]
Hi, 

I have a link that open a div with featherlight, I use "persist shared" because there is a form in the box that I validate in jquery (without "persist", it won't work because of duplicate fields). 
That works perfectly !
But I also have this exact same link elsewhere on my page : If I click on one link, close the box and open it again with another link, the box is empty ! 
Any idea ? 

Thanks !

**Comment by nicostem** [comment]
I've found the problem (which was in fact the same as here : https://github.com/noelboss/featherlight/issues/149 ). 
I used this on my links to open the box : 
`<a href="#" data-featherlight="#box" data-featherlight-persist="shared">link 1</a>
<a href="#" data-featherlight="#box" data-featherlight-persist="shared">link 2</a>`

But that didn't work, when I clicked on link 1 then link 2, it would open an empty box.
So I did this : 
`<a href="#" class="link">link 1</a>
<a href="#" class="link">link 2</a>`
and in JS : 
`$('.link').featherlight($('#box'), {persist: 'shared'});`

And this is working ! 
It could be nicer to be able to use the first method but it works so it's fine !

**Comment by weir** [comment]
This still isn't working. If you click link 1, then link 2, link 1 no longer works properly.

https://jsfiddle.net/asc4d5f1/

**Comment by nicostem** [comment]
Use this instead and it should work : 
`$('#link-1, #link-2').featherlight($('#box-1'), {persist: 'shared'});`
