### ISSUE TITLE
Uncaught type error

### ISSUE THREAD

**Issue by ygspasov** [noelboss/featherlight#211]
I'm receiving the following error when I try to use this plugin:
`Uncaught TypeError: $(...).attr(...).featherlight is not a function`

The function I'm using looks like this:
```
$(document).ready(function(){
  $(".gallery-icon a").attr("data-featherlight", "#mylightbox").featherlight();
});
```
What could be the problem?

**Comment by adamjw3** [comment]
@ygspasov what was the fix for this as i'm getting the same error 

Uncaught TypeError: $(...).featherlight is not a function
