### ISSUE TITLE
Empty white rectangle on click

### ISSUE THREAD

**Issue by ygspasov** [noelboss/featherlight#212]
I installed the plugin in a WP theme but when I click on a gallery image, a small empty white rectangle appears instead of the image itself. What could be causing the issue?
Screenshot attached 
![white rectangle](https://cloud.githubusercontent.com/assets/10303050/13374434/8a642350-dd8d-11e5-92d6-0a992c407e23.png)

**Comment by ygspasov** [comment]
Does anyone have an answer?

**Comment by marcandre** [comment]
Please ask questions on StackOverflow. Hopefully you will understand that without actual code, it's a guessing game?
