### ISSUE TITLE
Video did not load in Internet Explorer

### ISSUE THREAD

**Issue by anahitghazaryan** [noelboss/featherlight#216]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
       We monitor the tag `featherlight.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://jsfiddle.net/JNsu6/15/ .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

Hi,

Thank you for the good Lightbox plugin. Am using it on all my projects and i have one question from my last project.

I have an image gallery and within the image gallery i also have a video file with MP4 format. I noticed that in Internet Explorer 11 video did not Play. I see a popup which told me to save the video but it never plays the video within a popup.

Could you tell me why am facing this issue?

Thanks in advance.

![bugonie11](https://cloud.githubusercontent.com/assets/13948928/13944594/ca3e3a8e-f01f-11e5-97cd-67b5da30360c.png)

**Comment by marcandre** [comment]
Can you tell me why you ticked that this is a "Bug report" when it isn't?

**Comment by anahitghazaryan** [comment]
but this is a bug. Why the video should not be working on Explorer?

**Comment by anahitghazaryan** [comment]
If it is not a bug what is it? Please explain.
