### ISSUE TITLE
TinyMCE won't open texteditor

### ISSUE THREAD

**Issue by downup04** [noelboss/featherlight#217]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
       We monitor the tag `featherlight.js`.

 - [x ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://jsfiddle.net/JNsu6/15/ .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

Hi, i want to submit news on my page with feartherlight popup so i don't need a "whole" page for news submitting.

With featherlight (Won't open texteditor)
http://i68.tinypic.com/augi0h.jpg

if i go to the adress with fullscreen

http://i66.tinypic.com/2921u1x.jpg

Any idea why? A normal < . textarea . >< . /textarea  . > works fine.

**Comment by marcandre** [comment]
CSS can be tricky, I don't know why TinyCME reacts this way from being inside a featherlight, or what you need to change so it expands.

I do not consider this a bug of featherlight though. Good luck.
