### ISSUE TITLE
Is Featherlight intercepting React handleClick events?

### ISSUE THREAD

**Issue by karlhadwen** [noelboss/featherlight#220]
I've got the featherlight box working completely fine, and my React components too. Yet when I put my React components inside the lightbox, none of the handleClick events work from React. Is Featherlight intercepting handleClick events? My React components are working as expected outside of the lightbox.

**Comment by dylanjt** [comment]
@karlhadwen were you ever able to resolve this? I am running into a similar issue in Vue.
