### ISSUE TITLE
Resize featherlight with percentages: iframeHeight/iframeWidth.

### ISSUE THREAD

**Issue by albowler** [noelboss/featherlight#233]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
       We monitor the tag `featherlight.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://jsfiddle.net/JNsu6/15/ .

 - [x] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

I've noticed that percentages do not work with the iframeWidth/iframeHeight options:

`$.featherlight({iframe: 'test.html', iframeWidth: '80%', iframeHeight: '80%'});`

It would be a good feature for new responsive design iframe content.

Thank you!

**Comment by marcandre** [comment]
Featherlight will only transfer the data you provide to the iframe. The fact that '80%' does not work is not really featherlight's responsibility... Could be tweaked manually too I imagine.

Anyways, I don't think this needs to be "fixed".

For hints on how to address width/height of iframes: http://stackoverflow.com/questions/5867985/full-screen-iframe-with-a-height-of-100
