### ISSUE TITLE
Show navigation dots in gallery

### ISSUE THREAD

**Issue by garygreen** [noelboss/featherlight#240]
Is there any interest in this? If so may put together a PR.

![image](https://cloud.githubusercontent.com/assets/1702638/17347049/c19456b2-5905-11e6-8c85-0255ee7e0b40.png)

**Comment by marcandre** [comment]
featherlight aims to be minimal, so I think it's beyond it's scope.
It's easy to add those dots with the hooks featherlight provides (here `afterContent`), so the best thing would probably to provide the extra code & css to do this, say a wiki page.
I'll close this, but if you find something a bit more difficult to do than you think it should, let me know.

**Comment by garygreen** [comment]
It would be a nice enhancement, it's quite common across gallery / slider plugins to achieve this out the box - slickjs, owl carousel, and others. I know featherlight aims to be minimal, but it's a nice addition and provides a huge amount of feedback to the user that they are inside a gallery - other ways to provide this feedback are by showing a tiny amount of image on the left/right (something the other plugins do too). A feature which greatly improves usability and look and feel of the plugin is valuable and should be considered within the scope imo.

**Comment by robneu** [comment]
+1 to this being out of scope. If someone really wants to add it, featherlight already makes it possible. I'm sure you're not the only one interested in it, so maybe add some example code to the Wiki to hook it in?

**Comment by marcandre** [comment]
@garygreen given the code, I could modify the second gallery code example and include it, as a good example of customization. How about that?
