### ISSUE TITLE
iframeMinWidth iframeMinHeight

### ISSUE THREAD

**Issue by garygreen** [noelboss/featherlight#242]
These options are missing from the docs, had to dig thru source code to figure out how to get 100% width iframe.

**Comment by joao-pedro-alves** [comment]
@garygreen  And how did you get 100% width?

**Comment by marcandre** [comment]
I believe they are mentioned https://github.com/noelboss/featherlight#open-lightbox-with-iframe

> Options iframeWidth, iframeMinWidth, etc. or their corresponding data attributes are used as CSS when present
