### ISSUE TITLE
Content of lightbox always copied? Is this sane?

### ISSUE THREAD

**Issue by zevero** [noelboss/featherlight#245]
Feature request or bug report or question if this really is intended standard behaviour.
This is the simplest use case http://jsfiddle.net/4nLdswem/64/

```
<a href="#" data-featherlight="#mylightbox">Open element in lightbox</a>
<div id="mylightbox">This div will be opened in a lightbox</div>
```

The div is shown on the main page and A COPY!!! of my div (with the same id!!!) is inside the lightbox when the link is clicked.

I expect, that my div will be hidden/detached from the DOM on initialization (so I do not see it) and shown/attached into the lightbox on clicking the link. I expect that it IS and STAYS the same div, so I can attach other jquery logic to it.

In my view it is the only sane intent of this plugin. The persist option did not help in this respect.

**Comment by zevero** [comment]
I can use a string like http://jsfiddle.net/4nLdswem/71/ and use afterOpen to do initialisation on open ... but it is not pretty ...

**Comment by marcandre** [comment]
Typical use is to add `display="none"` to it (FL will fade it in) or put it inside a `<div display="none">`.

The issue with detached from DOM on initialization is that it could still show for a brief moment...

It won't be a copy with the `persist` option.

Does that resolve the issue for you?

**Comment by timint** [comment]
+1
