### ISSUE TITLE
Small size square of lightbox before opening full size (ajax)

### ISSUE THREAD

**Issue by flipflap** [noelboss/featherlight#246]
When I use featherlight to open a html site by ajax it shows a square size lightbox before loading the full size with content. Is there a way to handle that better? 

Thanks!

**Comment by marcandre** [comment]
Either specify a `loading` option to display some spinner, or hide it altogether (it has class `.featherlight-loading`), up to you.

PS: I won't copy-paste my stock comment about you completely disregarding my requests to ask questions on StackOverflow, but please do that next time.
