### ISSUE TITLE
How to add `allowfullscreen` to generated vimeo iframe?

### ISSUE THREAD

**Issue by mvaneijgen** [noelboss/featherlight#247]
I came across [this issue](https://github.com/noelboss/featherlight/issues/73) where someone was asked to create a new issues, but could not find it. 

How do you add `webkitallowfullscreen mozallowfullscreen allowfullscreen` to the generated vimeo iframe? Must I do it myself with a javascript hack or is there a option in the plugin to add attributes?

**Comment by marcandre** [comment]
The only way right now is via javascript (e.g. in `afterContent` callback).

There probably should be a better way though, and it probably should be the default.

We should probably create an option `iframeTemplate` which would contain 'iframe webkitallowfullscreen mozallowfullscreen allowfullscreen' by default.

Do you feel like writing a PR? Only "difficulty" is to not also generate `template: ...` in the CSS of that iframe.

**Comment by nguyenj** [comment]
@mvaneijgen I have [PR](https://github.com/noelboss/featherlight/pull/269) that should address this issue. Let me know if it works for you.

**Comment by marcandre** [comment]
Fixed & released
