### ISSUE TITLE
Is there a way to prevent the gallery from looping?

### ISSUE THREAD

**Issue by daniellevautier** [noelboss/featherlight#249]
Is there a way to prevent the gallery looping through the images e.g.
Disable left navigation when at image 1 of 10 and disable right navigation when at image 10 of 10 ?

Thank you,
Danielle

What kind of issue is this? (put 'x' between the square brackets)

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
       We monitor the tag `featherlight.js`.

 - [ ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://jsfiddle.net/JNsu6/15/ .

 - [x] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

**Comment by marcandre** [comment]
Yes, use CSS. The gallery will have class `featherlight-first-slide` and/or `featherlight-last-slide` if that's the case [#205].

For any other questions, please use StackOverflow
