### ISSUE TITLE
version not incremented 

### ISSUE THREAD

**Issue by GilbertJames** [noelboss/featherlight#251]
- [X ] Release version not incremented with issue 250 fixed.  Can the version be increased to 1.5.1.  This way the CDN providers pull the newest version. 

Example: https://cdnjs.com/libraries/featherlight

**Comment by marcandre** [comment]
Is the current "bug" causing you actual issues? A deprecated method doesn't mean it doesn't work anymore, just that it will eventually not work (say in jQuery 4.0)
