### ISSUE TITLE
beforeOpen triggers multiple times if event.ctrlKey is checked?

### ISSUE THREAD

**Issue by rokkamokka** [noelboss/featherlight#252]
What kind of issue is this? (put 'x' between the square brackets)
- [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
     something, or to understand why something isn't working the way you expect it to, use
     http://stackoverflow.com/questions/ask .
     Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
     We monitor the tag `featherlight.js`.
- [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
     starting from http://jsfiddle.net/JNsu6/15/ .
- [ ] Feature Request. Make sure there's no good way to do what you want first;
     consider asking on http://stackoverflow.com/questions/ask first.

I've encountered a strange issue while trying to make featherlight disregard ctrl-clicks and middle mouse clicks. Minimally viable example fiddle here: http://jsfiddle.net/JNsu6/261/

If you look at the console while ctrl-clicking the featherlight link, you can see beforeOpen triggers multiple times. Furthermore, it triggers one additional time for every ctrl-click you make, and the last trigger always gets event.ctrlKey === undefined. For example, ctrl-clicking it upon page load gives two triggers. Ctrl-clicking it again makes it trigger three times. Do it again and it triggers four times. In all cases, the last trigger always gets event.ctrlKey === undefined.

I've only tested this in Chrome. I've looked at the featherlight source but can't figure out how this could even occur.

**Comment by marcandre** [comment]
Interesting issue. **Thanks for the fiddle**!

There are two bugs here.
First, what you're seeing is FL's `autoBind` in action, failing to recognize it already bound that link.
Second, autoBind resends a click event but doesn't forward key modifiers.

An easy way out for now is to remove the `data-featherlight` attribute and bind it manually , e.g. `$('a').featherlight()` works in your simple example.

**Comment by rokkamokka** [comment]
I see. It seems the event propagation is not stopped, leading to the autobind becoming confused. Adding event.stopPropagation() in the beforeOpen callback also fixes the issue in this case.

**Comment by marcandre** [comment]
Right, but I thought you didn’t want to stop the propagation… If you do,
right, that will solve it too.

**Comment by timint** [comment]
I'm too having an issue with event.ctrlKey and event.shiftKey. I'm trying to bypass the lightbox and restore normal browser behavior when either key is held and clicking a link.

'Open' seems to be fired twice and event.ctrlKey is missing for the second fire.

**Comment by marcandre** [comment]
I've pushed some tweaks to the 'autobind' feature so that the event is used directly instead of triggering an artificial click.

**Comment by marcandre** [comment]
@timint Using current `master`, you should be able to check the event in `beforeOpen` and return `false`

**Comment by timint** [comment]
Works like a charm!
`beforeOpen: function(e){ if (e.ctrlKey || e.shiftKey) return false; }`

**Comment by marcandre** [comment]
Closing, as this has been released.
If anyone has an idea for Featherlight to know when it should respond to ctrl/shift click or not by default, let me know. Seems hard to know.

**Comment by timint** [comment]
This is what I did. Perhaps anyone would like an option to disable the events.
https://github.com/timint/featherlight/commit/7277c45961e237e5673bf11269996d379d7e592d

**Comment by timint** [comment]
Correction, make sure there is an event or an error will occur when opening a featherlight from the command $.featherlight(url).

```
		open: function(event){
			if (event && (event.ctrlKey || event.shiftKey)) return false;
```
