### ISSUE TITLE
Not able to select Customized radio button

### ISSUE THREAD

**Issue by sridhand** [noelboss/featherlight#253]
Customized radio button not working in Modal window. Same radio button working fine in html page.
Sample code is here 
http://jsfiddle.net/dsriniudt/JNsu6/264/

Any suggestion great help.

**Comment by marcandre** [comment]
The radios, when copied by FL, are no longer bound.
Use the `persist` option (so they're not copied), or else figure out a way for the customized radios to use delegated events.
