### ISSUE TITLE
ajax post / loading spinner only

### ISSUE THREAD

**Issue by ash-f** [noelboss/featherlight#254]
Please add ajax "post" support with passing parameter with "data" attributes.

Also loading spinner only mode would be nice to wait loading ajax content.
So I can swap Featherlight instance later.

**Comment by marcandre** [comment]
Ajax post: You can customize any options send to Ajax, including `type: 'Post'` using either the `field:ajaxoptions` event or `data-parsley-remote-type="post"`

Spinner: You can use `.featherlight-loading` and CSS to show what you want while loading.
