### ISSUE TITLE
Valid function raises error when used for `beforeOpen`

### ISSUE THREAD

**Issue by K-Thompson** [noelboss/featherlight#258]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
       We monitor the tag `featherlight.js`.

 - [X ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://jsfiddle.net/JNsu6/15/ .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

The reason for this will be best understood if the page content loaded into the `iframe` is long enough that it requires vertical scrolling to view completely.

This works:

`$.featherlight({iframe:` 'http://localhost', iframeWidth: '98%' });

Notice if you use a mouse wheel to scroll the contents, when you reach the bottom or top of the content and continue to scroll (using the wheel), the page behind Featherlight starts to scroll. The result is, when the user closes Featherlight, they are not at the same page location as they were when they launched a lightbox. Not so nice.

The solution for this, should be simple -- temporarily turn off the parent page's Y-axis scrollbar. To do this, I want to hook the `beforeOpen` event. To test my JavaScript pattern, below works. Featherlight does not open.

`$.featherlight({iframe:` 'http://localhost', iframeWidth: '98%' }, {beforeOpen: function () {return false; }});

This function fails however:

`$.featherlight({iframe: 'about:blank', iframeWidth: '98%' }, {beforeOpen: function () {$("body").css({"overflow-y": "hidden"}); }});
`

The error raised in the console is:

> featherlight.js:209 Featherlight: no content filter found  for "[object Object]"

Similarly, I would expect this to work 

`afterClose : function () {$("body").css({"overflow-y": "scroll"});`

**Comment by marcandre** [comment]
Next time, please provide working example, as requested.

Also always double check the documentation. Especially when you get an error message from the library you're using instead of a low level error.

Just combine your two objects into one.
