### ISSUE TITLE
Close button should be <button>, have accessible text.

### ISSUE THREAD

**Issue by mrwweb** [noelboss/featherlight#260]
At present, the close button is just a `<span>`, so it can't have focus and therefore can't be navigated to with a keyboard. It should be made with a focusable element, probably a `<button>`. Further, that button needs a text label of some form. That could be done either with a span with class screen-reader-text or an aria-label attribute.

**Comment by marcandre** [comment]
:+1:, care to provide a PR?

**Comment by mrwweb** [comment]
Unfortunately, no. Sorry.

Given this, #259, and a tight project deadline, I needed to find a different accessible-out-of-the-box lightbox.

**Comment by marcandre** [comment]
Ok, let me see what I can come up with, then.

A `<button>` makes sense, but an `<a>` would make the CSS easier to reset... Any objection?

**Comment by mrwweb** [comment]
The general a11y rule is to use links for things that go to other pages (or page-like things) and buttons for actions. Therefore, a button is the preferable element.

**Comment by marcandre** [comment]
I agree. Just not sure I want to add rules like `button::-moz-focus-inner` to reset it. Let me try

**Comment by marcandre** [comment]
Not so bad. Changed it to a `<button>`.

**Comment by marcandre** [comment]
Fixed in `1.6.0`
