### ISSUE TITLE
Can't get custom controls on HTML5 video to work within featherlight pop up

### ISSUE THREAD

**Issue by HandHugs** [noelboss/featherlight#263]
I have a video on my page that I want to open with lightbox. The video plays fine on the page, but when I open it in the lightbox, the controls (which are custom and controlled with js initiated with window.onload) stop working. 

also when i set display:none the div that the video is in, it wont show on open...
any help??

**Comment by HandHugs** [comment]
Ok so i got the hidden div to show so sorry about that but I still can't get the controls to work. I am guessing i have to put the js that controls them in the 
afterOpen function, but I can't even get a simple console.log() or alert to work with those controls. 

http://jsfiddle.net/24cz9jok/3/

What am I missing??

**Comment by marcandre** [comment]
I think you're binding manually *and* binding automatically?

**Comment by HandHugs** [comment]
@marcandre  Can you show me in the fiddle how to get an alert or any reaction from afterOpen? Your response doesn't help me fix the problem. I know I am doing something wrong, but I can't figure it out.

**Comment by HandHugs** [comment]
Anyone? I just want an example of a fiddle or codepen where the afterOpen is working

**Comment by marcandre** [comment]
Your fiddle uses a really old version of featherlight. Making sure you are using the latest release of a library should *always* be the first thing to do.

Here's an example: http://jsfiddle.net/marcandre/JNsu6/273/
