### ISSUE TITLE
featherlight responds GET 404 Error with different urls of the same code. 

### ISSUE THREAD

**Issue by joeporterme** [noelboss/featherlight#265]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
       We monitor the tag `featherlight.js`.

 - [ X] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://jsfiddle.net/JNsu6/15/ .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

Here is a copy of code that returns 404.  Even though the Response in firebug actually shows shows the code from the url:
https://jsfiddle.net/f53yhca1/

This one works, changed the file name and path but the file is the same exact code:
https://jsfiddle.net/hk7t31rk/

So weird, im leaving it so it can just work, but i prefer the file structure of the first example.

**Comment by marcandre** [comment]
Your fiddles have PHP code in them, not sure how I'm supposed to help. I can't see how one would work and the other wouldn't that would be featherlight's fault.

Unless I'm provided a working example, there's just no way for me to help here.
