### ISSUE TITLE
option to not wait for the iframe to load before displaying

### ISSUE THREAD

**Issue by ma2thieu** [noelboss/featherlight#267]
What kind of issue is this? (put 'x' between the square brackets)

 - [ X] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

I would be nice to have an option to open the lightbox with an iframe content instantly, without waiting for the on('load')
I have a page with different trackers (google analytics, piwik, ...) and the popup is very slow to open because it waits for all the javascripts to be loaded before opening

**Comment by marcandre** [comment]
I doubt I'll integrate a setting for that, maybe if a lot of people chime in.

There are many different ways to go around that though. You can overwrite the `iframe` content filter, write your own, or trigger a false `load` event from the `beforeContent` callback.

**Comment by ma2thieu** [comment]
Thanks I followed your advice and defined a new content filter like that : 
```
        $.featherlight.contentFilters.iframe2 = {
            process: function(url) {
                var $content = $('<iframe/>');
                $content.hide()
                    .attr('src', url)
                    //.css(structure(this, 'iframe'))
                    .appendTo(this.$instance.find('.' + this.namespace + '-content'));
                return $content.show();
            }
        };
        $.featherlight.defaults.contentFilters.unshift('iframe2');
```

although I don't see how to call structure() ?

**Comment by marcandre** [comment]
You can't call it, it's not public, API can change...
