### ISSUE TITLE
Iframe scrolling only background with ios

### ISSUE THREAD

**Issue by mgk89** [noelboss/featherlight#270]
Hi, 

When opening light Box with an iframe in it on ios it only scrolls the main page. The popup seems to be fixed and does not scroll at all. Also if there are inputs in the iframe, there is no chance to click on them and fill them out. 

Any idea how to prevent this? 

Thank you in advance

**Comment by marcandre** [comment]
I'm afraid it has been reported already (#77) and no solution has been provided for now.

Closing this one, please follow #77
