### ISSUE TITLE
Content with iframe layout messup

### ISSUE THREAD

**Issue by JackPoint** [noelboss/featherlight#280]
- [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://jsfiddle.net/JNsu6/15/ .

Example http://jsfiddle.net/d8e6svf4/

When the content contains an iframe, it add's the class featherlight-iframe automatically. I understand this is usefull when your content is an iframe, but in my case not. I have textual content that includes an iframe. 

The problem for me is that .featherlight-iframe .featherlight-content has a padding: 0; this messes with my layout.

Is this a bug? Should the class featherlight-iframe only be added when the full content is an iframe?
I think it's in this part: https://github.com/noelboss/featherlight/blob/0e70f2b90b2e0f1999a4c7ff22961cc0f118e69d/src/featherlight.js#L239

**Comment by marcandre** [comment]
I have to agree that this looks like a bug. I'll change it.

**Comment by JackPoint** [comment]
Thanks for the fix. When do you release a new version so I can use this?

**Comment by marcandre** [comment]
My laptop is out or order and I'm travelling, I'll be back next tuesday, sorry for the delay.

**Comment by marcandre** [comment]
Released 1.7.1, thanks again for the report
