### ISSUE TITLE
The half of the images are not loaded

### ISSUE THREAD

**Issue by Galterian** [noelboss/featherlight#282]
Hello,
We have a problem on our site https://www.keystonecarpet.net with this library, explained as bug report bellow. The problem is that the half of the images are not loaded at all.

 - [ ] Bug report: On https://www.keystonecarpet.net you can see on the console that the featherlight throws an exception:
featherlight.min.js;wa3dae0b588724d549:1 Uncaught TypeError: **t.on is not a function**
    at Function.attach (featherlight.min.js;wa3dae0b588724d549:1)

I think that there is some problem with reading the configuration. E,g. from the source:
```
			/* Only for openTrigger and namespace... */
			var namespace = config.namespace || Klass.defaults.namespace,
				tempConfig = $.extend({}, Klass.defaults, Klass.readElementConfig($source[0], namespace), config),
				sharedPersist;

			$source.on(tempConfig.openTrigger+'.'+tempConfig.namespace, tempConfig.filter, function(event) {
				/* ... since we might as well compute the config on the actual target */
```

We are using the min version, and those "t.on" is actually "$source.on" from the code above.

Can you check this problem?

PS: on our other site https://nationalflooringandsupply.yourgreatfloors.com we are using the same featherlight version but this problem does not occur there.

**Comment by marcandre** [comment]
I'm sorry you're having problems.
While I gladly volunteer to fix bugs *in the library*, your request sounds like you'd like me to fix bugs *in your website*.
Contact me directly if you want to hire me to help, otherwise you will have to figure out what is going wrong.
