### ISSUE TITLE
Consider UMD support

### ISSUE THREAD

**Issue by gsantiago** [noelboss/featherlight#283]
It would be very nice to add [UMD support](https://github.com/umdjs/umd/blob/master/templates/jqueryPlugin.js) for this plugin.

Currently, it depends on jQuery globally defined. So, even using tools like Browserify and Webpack I still have to set jQuery globally only for this plugin.

**Comment by marcandre** [comment]
Indeed.
I'd love to port it to ES6, and Babel would create the UMD support out of the box...

**Comment by MikhailRoot** [comment]
Hi guys! First thank you for great library. I've wrapped it in UMD as suggested here's PR for `featherlight.js`
https://github.com/noelboss/featherlight/pull/377
