### ISSUE TITLE
[Feature Request] Fix close icon to the modal frame not content

### ISSUE THREAD

**Issue by operapreneur** [noelboss/featherlight#288]
This would fix a UX error. When the content of the modal is larger than the visible content frame you can scroll the content and thus scrolling the close button. Scrolling the content should NOT move the close button.

**Comment by marcandre** [comment]
Thanks.
Indeed, this is a known bug.
Closing in favor of #273

**Comment by Eduruiz** [comment]
Hello, I saw #273 but I don't think it solves that issue.
I tested it on the live version of featherlight default and it keeps happening, if the content is big enough in height to generate a y axis scrolling, when you scroll you "loose" the close button who gets hidden on the overflow.
![04-12-17--13 09 34](https://user-images.githubusercontent.com/1951631/33559864-4678daea-d8f5-11e7-82a9-1923d70c2a5b.jpg)
