### ISSUE TITLE
Swipe doesn't work on iPhone

### ISSUE THREAD

**Issue by ynamite** [noelboss/featherlight#289]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
       We monitor the tag `featherlight.js`.

 - [ x ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://jsfiddle.net/JNsu6/15/ .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

Swipe doesn't work on iPhone (latest iOS). See the fiddle:
http://jsfiddle.net/JNsu6/400/

Any idea what's happening? As far as I can determine the swipeAwareConstructor is successfully set but the swipe events are just not being triggered. 

Thanks a bunch

**Comment by marcandre** [comment]
Very odd, I thought this had been working for ever and nothing has changed recently. I'll have to dig deeper.

**Comment by marcandre** [comment]
Oh, you just need to check [the documentation](https://github.com/noelboss/featherlight#gallery-on-mobile-devices) and include a library that support `swipeleft` and al. events. Our own demo wasn't though, so I fixed that.
