### ISSUE TITLE
Bug: radio buttons get cleared when closing and re-opening modal

### ISSUE THREAD

**Issue by ryancwalsh** [noelboss/featherlight#291]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
       We monitor the tag `featherlight.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://jsfiddle.net/JNsu6/15/ .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

**Check out the demo: http://jsfiddle.net/a2vek7f5/2/**

**Comment by ryancwalsh** [comment]
Never mind. I didn't know about `$.featherlight.defaults.persist = true;`

It seems surprising that it's not the default.

**Comment by ryancwalsh** [comment]
Maybe it would be better to at least restore the initial "checked" values of radio buttons that existed upon page load.

**Comment by marcandre** [comment]
Thanks for the feedback.
The `persist` option is there for this kind of thing. Otherwise we use jQuery's `clone` which duplicates most but not all state.
