### ISSUE TITLE
[BUG REPORT] no content filter found

### ISSUE THREAD

**Issue by jenkk** [noelboss/featherlight#294]
Hello!  
I think I've come across a bug, maybe it's nothing and maybe I'm just stupid (Probably the latter 😆)  
Here is the error reported by the console:
```Featherlight: no content filter found  (no target specified)
getContent @ featherlight.min.js:8
open @ featherlight.min.js:8
i @ featherlight.min.js:8
(anonymous) @ featherlight.min.js:8
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3
```  
Here is my code where I'm _trying_ to use Featherlight.
```  
<a href="https://www.youtube.com/embed/'+videoId+'" data-featherlight="iframe" data-featherlight-iframe-allowfullscreen="true" data-featherlight-iframe-width="940" data-featherlight-iframe-height="529">
```  
Any help would be majorly appreciated, I'm trying to wrap this project up as soon as possible :)

**Comment by marcandre** [comment]
If you’ve found a bug, you must provide a minimal example in a CodePen, starting from http://jsfiddle.net/JNsu6/15/ .

**Comment by crobinson42** [comment]
@jenil I have been using the lib in my website for over a year and just started experiencing the same error `Featherlight: no content filter found  (no target specified)` and I haven't changed anything 👎

**Comment by marcandre** [comment]
@crobinson42 sorry about the troubles you are having. Please try to find a minimal reproducible example.
