### ISSUE TITLE
Javascript error: SCRIPT438: Object doesn't support property or method 'blur'

### ISSUE THREAD

**Issue by oystersauce8** [noelboss/featherlight#295]
- [x] Bug report.

I have recently implemented featherlight replacing the older colorbox plugin.

Recently we've been getting complaints from MS IE/Edge users about this error:
`SCRIPT438: Object doesn't support property or method 'blur'`

In our site, Featherlight is invoked by clicking on a <svg> image.
After some digging, I found that featherlight tries the .blur() method like this:

    document.activeElement.blur();

but it turns out, some OS/browser combinations throw an error when attempting call .blur() on on a document.activeElement which is an <svg>
(https://allyjs.io/tutorials/focusing-in-svg.html)

**Comment by oystersauce8** [comment]
Wrapped my solution in to https://github.com/noelboss/featherlight/pull/296

**Comment by marcandre** [comment]
:+1:
