### ISSUE TITLE
Select component doens't work properly under Featherlight Dialog

### ISSUE THREAD

**Issue by xurdep** [noelboss/featherlight#299]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
       We monitor the tag `featherlight.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://jsfiddle.net/JNsu6/15/ .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

Hi Noel...
I think I found a bug, I uploaded to JSFiddle the simple code where you can see the bug (select component doesn't update under your dialog). 

This is the link: http://jsfiddle.net/xurdep/pbjdux00/7/

Thank you.
Regards

**Comment by marcandre** [comment]
Thanks for the fiddle.

By default, featherlight copies the content given. So avoid IDs and do a local find within callbacks (e.g. `this.$element.find(...)`).

Or else use the `persist` option.

**Comment by xurdep** [comment]
Sorry marcandre...
I didn't understand your answer... I need to open featherlihg dialog with a custom option selected.
Can you show me an example?
Thanks
