### ISSUE TITLE
width

### ISSUE THREAD

**Issue by marcandre** [noelboss/featherlight#30]
The css requests a width of 60%.

Is there a good reason for that?

In my code base, I had to override this with `inherit` and it just looks much better.

I think 60% can look very wide, and for content that is smaller it can look wierd.

@noelboss I propose to remove that line, what do you think?

**Comment by negativefix** [comment]
On larger screens min-width: 30% is too wide as @marcandre stated.  I came across this issue while I was trying to display static width content inside featherlight. At first, I thought there was a problem with my markup and styling but then realized it's how featherlight behaves. I vote for removal of min-width.

**Comment by marcandre** [comment]
Removed in `master`. Thanks
