### ISSUE TITLE
Printing featherlight content appear 2 duplicated pages.

### ISSUE THREAD

**Issue by sonans202** [noelboss/featherlight#304]
When print the featherlight content,  (right-click the popup and select print). The print preview has shown duplicated pages, supposedly only have 1 page instead of 2.  And some CSS style for the lightbox is gone as well.

These bugs i mentioned can be found in the demo website. just click on one of the popup and right click select print.
http://noelboss.github.io/featherlight/

Any help / feedback on this is much appreciated.

Ps: I'm using Chrome.

Thanks
KK

**Comment by alexcwatt** [comment]
With 1b20a0938a16aa0ab2d93e8ef14ae8b6ca6f6954 in 1.7.8, there is a `with-featherlight` class applied to the `html` node when the featherlight content is open. I am using this with a `@media print` style to hide everything else.

```
@media print {
	@page {size: landscape}

	html.with-featherlight body > :not(.featherlight) {
		display: none;
	}
}
```

**Comment by sonans202** [comment]
Thank you @alexcwatt! It works! I didn't noticed the "with-featherlight" from the first place and thankfully that it can be fixed by just using only CSS.

**Comment by marcandre** [comment]
Great stuff @alexcwatt . I've included your CSS in the latest release. Thanks to all.

**Comment by grafxdesign** [comment]
Ummmm.... Doesn't this now make EVERYTHING print landscape????
