### ISSUE TITLE
How is it responsive.

### ISSUE THREAD

**Issue by jjwallace** [noelboss/featherlight#309]
No responsive support found but mentioned in the document tag

**Comment by robneu** [comment]
![1colqsalew](https://user-images.githubusercontent.com/2184093/27243388-8e6e39fc-52af-11e7-82ef-3a1b2cc7ad12.gif)

**Comment by marcandre** [comment]
Great demo @robneu :1st_place_medal: 
Moreover the gallery it behaves differently for touch devices.
Anything you were looking for in particular @jjwallace ?
