### ISSUE TITLE
Website lists version 1.7.1 as latest

### ISSUE THREAD

**Issue by flaviocopes** [noelboss/featherlight#315]
What kind of issue is this? (put 'x' between the square brackets)

 - [X ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://jsfiddle.net/JNsu6/15/ .

![screen shot 2017-07-18 at 17 01 58](https://user-images.githubusercontent.com/11783388/28324077-da06cf2a-6bda-11e7-9fd0-f9d0da895ca8.png)

I didn't realize we're now at 1.7.7, is there a reason or simply was forgot and left behind? Worth updating or you'll get older versions being installed.

**Comment by marcandre** [comment]
Sorry about that, I often forget to push to the `gh-pages` branch. I should write a release script...

Fixed. Thanks for reporting this.
