### ISSUE TITLE
Bug? tabindex -1 on form elements?

### ISSUE THREAD

**Issue by mhulse** [noelboss/featherlight#318]
Great plugin, thanks!

http://jsfiddle.net/JNsu6/439/

I would expect to not have my form elements modified with a `tabindex`.

Seeing this happening in latest Chrome/macOS. Featherlight 1.7.6.

**Comment by marcandre** [comment]
I'm really sorry about this, it's a [known bug](https://github.com/noelboss/featherlight/issues/285) I'm eager to fix but haven't quite finished. Closing in favor of #285.
