### ISSUE TITLE
Show chart.js canvas element in featherlight lightbox?

### ISSUE THREAD

**Issue by indig0blue** [noelboss/featherlight#321]
I am trying to display a chart.js chart in a featherlight lightbox. The chart is a canvas element. For some reason, I can't get it to show.

Can anyone offer insight into this?

Thank you so much.

**Comment by josephbydeign** [comment]
I am having the same issue as well with signature_pad canvas. I am trying to initialise the canvas with an "afterOpen" function

**Comment by marcandre** [comment]
Should work with `afterOpen`, or specifying a `content` (can be a promise), or probably the best way would be to specify a content filter for this.
Best for question: make a minimum example, and use StackOverflow
