### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by chimmel** [noelboss/featherlight#323]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
       We monitor the tag `featherlight.js`.

 - [x] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://jsfiddle.net/JNsu6/15/ .

 - [ ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

This was working before but now it won't and I don't understand why not, what the difference could be... trying to load ajax page from link href... results

`Uncaught TypeError: a(...).load is not a function
    at b.process (featherlight.min.js:8)
    at b.getContent (featherlight.min.js:8)
    at b.open (featherlight.min.js:8)
    at HTMLAnchorElement.i (featherlight.min.js:8)
    at HTMLAnchorElement.dispatch (jquery-3.1.1.slim.min.js:3)
    at HTMLAnchorElement.q.handle (jquery-3.1.1.slim.min.js:3)`

Trying `<a href="Hello, world" data-featherlight="text">Example</a>` results

`Uncaught TypeError: c.$instance.fadeIn is not a function
    at b.open (featherlight.min.js:8)
    at HTMLAnchorElement.i (featherlight.min.js:8)
    at HTMLAnchorElement.dispatch (jquery-3.1.1.slim.min.js:3)
    at HTMLAnchorElement.q.handle (jquery-3.1.1.slim.min.js:3)`

??

**Comment by marcandre** [comment]
Is it possible to have a working example?

**Comment by marcandre** [comment]
Oh, you are using the [**slim** version of `jquery`](https://stackoverflow.com/questions/35424053/what-are-the-differences-between-normal-and-slim-package-of-jquery) which doesn't include `load`. Use the full fledged version.

**Comment by chimmel** [comment]
Thanks!
