### ISSUE TITLE
closeOnClick: 'anywhere' prevents use of gallery

### ISSUE THREAD

**Issue by BWPanda** [noelboss/featherlight#324]
When `closeOnClick` is set to `anywhere`, you can no longer click on the previous/next buttons to navigate through a gallery. Clicking these buttons closes the gallery instead (using the left/right keys on your keyboard still works ok though).

Here's an example: http://jsfiddle.net/JNsu6/448/

I'd suggest making it so that the previous/next buttons override the `closeOnClick` behaviour (I can't think of a situation in which you'd not want the previous/next buttons to work...).

**Comment by marcandre** [comment]
Agreed. Care to provide a PR to address this?

**Comment by BrenzoE** [comment]
This issue is solved
