### ISSUE TITLE
Bind featherlight without opening modal?

### ISSUE THREAD

**Issue by iamkeir** [noelboss/featherlight#327]
Is it possible to bind/setup/init featherlight _without_ also opening the modal? 

Currently `var modal = $.featherlight($target,config)` binds and then opens. 

I have worked around it for now by immediately invoking `modal.close()` but this feels hacky.

Possible options:

1) New config option `openOnBind (true/false)`

2) Bind should _not_ also open by default - user can choose to use `.open()` as needed.

Would welcome your thoughts, @marcandre - happy to provide a PR based on what approach you think is best (if any).

**Comment by marcandre** [comment]
`$target.featherlight(config)`.
For other questions, please respect my wishes and ask them on StackOverflow

**Comment by marcandre** [comment]
Better answer: https://stackoverflow.com/questions/46336147/bind-featherlight-to-modal-content-but-without-also-opening-the-modal/46347908#46347908
