### ISSUE TITLE
Please state that you need Jquery.min on comments.

### ISSUE THREAD

**Issue by Enkii-Muto** [noelboss/featherlight#329]
Hello =)

I really like your plugin and your philosophy of how light it should be. I'm still beginning with it so you might me see here with actual issues but... guys, can you do one big favour for people like me that would consider their own code to be wrong rather than the CDN?

State on the documentation (I only found that you require Jquery 1.7) or on the comment of your JavaScript that despite you calling it "ultra slim", it actually requires Jquery.min? It took me quite a while to figure that out since I never needed anything other than slim for bootstrap and other features to run, so it never crossed my mind.

I know it is stupid but it will take less than 5 minutes for you to add that and it will save time for the next idiot with the same problem XD Thanks for the awesome plugin and best wishes.

 - [x] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

**Comment by marcandre** [comment]
IIC, you'd like me to add that Featherlight requires jQuery?

Featherlight calls itself "a very lightweight **jQuery** lightbox". The installation section is very clear that jQuery is required. If someone doesn't include jQuery correctly, Featherlight detects it and issues a message in the console to that effect.

**Comment by Enkii-Muto** [comment]
I'm not asking you to say the Jquery plugin requires Jquery.

I'm asking to state that it needs at least jquery **.min** and not other compressed versions such as **slim or slim minified**, not much different than what you currently have stating it requires a certain version of the Jquery.

**Comment by marcandre** [comment]
I made a change in the ReadMe.

**Comment by marcandre** [comment]
I also added a runtime check.

**Comment by Enkii-Muto** [comment]
Thank you =)
