### ISSUE TITLE
Options are not getting accepted in featherlight

### ISSUE THREAD

**Issue by vincelawdev** [noelboss/featherlight#333]
I was using 1.7.1. I thought there might be a problem with it so I tried 1.7.9 and the code below doesn't work for me.

```
var options = {
        variant: 'test-lightbox',
        otherClose: '.test-lightbox-close',
        closeIcon: ''
};

$('.test-lightbox-link').featherlight(options);
```

I noticed that my options no longer work when I pass in do not get used at all. I still see the default featherlight CSS applied.

However, it works properly if I try to use data-featherlight-option attributes in my hyperlink code.

**Comment by marcandre** [comment]
Are you using the autobinding feature also? Remove `data-featherlight` from your HTML attributes.

**Comment by vincelawdev** [comment]
Thanks. That worked. I am not sure how I managed to use data-featherlight attribute before. I changed it to my own custom data-lightbox attribute and it works fine now.
