### ISSUE TITLE
Open image like facebook image display file chars

### ISSUE THREAD

**Issue by trippo** [noelboss/featherlight#334]
If i try to open a facebook profile image like https://graph.facebook.com/10214295368558932/picture?type=large&width=200&height=200

lightbox display encrypted chars

like this example http://jsfiddle.net/L3yyzfob/

**Comment by marcandre** [comment]
Specify a `data-featherlight-type="image"`, as featherlight is using the wrong content-filter because the URL doesn't have .jpg or similar in it.
