### ISSUE TITLE
Featherlight Gallery with mixed content: featherlight-iframe class wont be removed

### ISSUE THREAD

**Issue by SvenDeKa** [noelboss/featherlight#340]
when you use the featherlight-gallery with mixed content of iframe and any other type the ".featherlight-iframe" (.<namespace>-iframe to be precise) won't be removed once it is added.

this is due to:
`setContent: function($content){`
`			var self = this;`
`			/* we need a special class for the iframe */`
`			if($content.is('iframe')) {`
`				self.$instance.addClass(self.namespace+'-iframe');`
`			}`
`... `

and will work if changed to:
`setContent: function($content){`
`			var self = this;`
`			/* we need a special class for the iframe */`
`			if($content.is('iframe')) {`
`				self.$instance.addClass(self.namespace+'-iframe');`
`			} else {`
`				self.$instance.removeClass(self.namespace+'-iframe');`
`			}`
`...`

**Comment by marcandre** [comment]
Indeed, good catch. Fixed & released. Thanks
