### ISSUE TITLE
Printer CSS is broken

### ISSUE THREAD

**Issue by darkain** [noelboss/featherlight#342]
- [X] Bug report.

https://github.com/noelboss/featherlight/commit/5a8d3596a8bb9d9ba19a63c8ea56de01cb77a7a6#diff-ad2dc0999b9a5bcb0bde649fac03da12R157

`@page {size: landscape}`

This should *NOT* be applied globally. While it may work for some sites, it absolutely breaks others. For instance, I'm running an ecommerce web site which uses Featherlight to display product images. Updating to the latest version of Featherlight introduced this code, and now I can no longer properly print out customer invoices or shipping labels, because they're all forced into landscape printing.

**Comment by marcandre** [comment]
Absolutely. Sorry this flew under my radar. Fixed & released.

**Comment by darkain** [comment]
Thanks!
