### ISSUE TITLE
Gallery swipe bug on multi display systems

### ISSUE THREAD

**Issue by ScotsScripts** [noelboss/featherlight#345]
The gallery swiping functionality does not function properly on multi display systems where one monitor is a touch screen (like a Surface Pro) and the other is non-touch.

What happens in this situation is the CSS next/prev that should show up on mouse hover do not.

Seems like the mouse hover stuff should show up on all monitors, regardless if it's a touch screen. It's no like it's going to know someone is hovering with their finger. Anyone know how to make this happen?

I reported this a couple years ago and it appeared something was going to be done to fix it, there was some discussion, but still it's not working right.

**Comment by marcandre** [comment]
You can simply override the `featherlight-swipe-aware` CSS rules. I think this will work.

```
.featherlight-swipe-aware .featherlight-next,
.featherlight-swipe-aware .featherlight-previous {
	display: inherit;
}
```

PR welcome for a better solution
