### ISSUE TITLE
Avoid using @media all

### ISSUE THREAD

**Issue by Flui** [noelboss/featherlight#346]
Why is '@media all' used here, as it adds only complexity and will be transformed to '@media' with cssnano which is invalid for ie11.

https://github.com/noelboss/featherlight/blob/569ff6a3e67220735d5577ae7af189a177b5791d/src/featherlight.css#L8

**Comment by peer0812** [comment]
I second that. I used the featherlight.css as _featherlight.scss in my Gulp setup with cssnano. IE11 didn't load the CSS styles for the featherlight element... 
Like Flui I think the "@media all" is not neccessarily needed and could be removed. 

Thanks @Flui for pointing this out. This helped me a lot.

**Comment by marcandre** [comment]
Fixed in the next release, thanks.

**Comment by Flui** [comment]
thanks in advance
