### ISSUE TITLE
Are my phone hacked

### ISSUE THREAD

**Issue by oralee123** [noelboss/featherlight#367]
What is cdn rawgit !! Some have sent me a link on Snapchat and I was so stupid and pressed on it. My phone went out and turned on by itself. Have I hacked something. Has the person got all my stuff on the phone or snapchat?

**Comment by oralee123** [comment]
What is cdn rawgit !! Some have sent me a link on Snapchat and I was so stupid and pressed on it. My phone went out and turned on by itself. Have I hacked something. Has the person got all my stuff on the phone or snapchat?

**Comment by marcandre** [comment]
http://lmgtfy.com/?q=what+is+cdn+rawgit
