### ISSUE TITLE
Loading Featherlight after using jQuery noconflict

### ISSUE THREAD

**Issue by jayesbe** [noelboss/featherlight#371]
- [x] Question. 
 - [x] Feature Request. 

I am using featherlight in an environment where jQuery 1.8 is required. This version is too ancient.. so I load jQuery 3 dynamically. 

```
    var $window = window;
    loadScript('//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js', function() {
            var jQ = $.noConflict(true);
            if (!$window.jQuery) {
                $window['jQuery'] = jQ;
                $window['$'] = jQ;
            }
            loadDeps(jQ);
   });
```

the loadDeps() method call then loadScript's featherlight. 

However.. featherlight is instantiated with jQuery 1.8.  Not 3.3.1.

When I inspect the page I can see jQuery 1.8 is loaded.. then I see the jQuery 3.3.1 being loaded.. I then see featherlight 1.7.13 being loaded in that order.

Is what I am trying to do not possible ?  does there need to be a change to featherlight to support this requirement ?

**Comment by marcandre** [comment]
I believe Parsley will use `window.jQuery` when loaded. So if you loaded it just before calling `$.noConflict` above (i.e. when `window.jQuery` is still 3.3.1), you should have what you want.

**Comment by jayesbe** [comment]
Thanks @marcandre I'll look into this further.
