### ISSUE TITLE
Page 'shifts' on opening and closing

### ISSUE THREAD

**Issue by jcamachott** [noelboss/featherlight#374]
Hi, forgive me if this was covered before. Searched and didn't find anything.

The issue I'm having is when a page is scrollable, and I open an image lightbox, it opens the lightbox and removes the scroll from the page. This causes the page to shift a bit. Is this avoidable at all? As I'm using plain image lightboxes I won't ever need to scroll whats inside the lightbox so its fine if the background page scrolls. 

Not using any js...only the data attributes.

Thanks.

**Comment by marcandre** [comment]
I think this is due to the following CSS rule:

```
html.with-featherlight {
	/* disable global scrolling when featherlights are visible */
	overflow: hidden;
}
```

I think you'll get what you want if you simply override it (with `overflow: inherit`).

**Comment by anobjectn** [comment]
I recommend this:
`html.with-featherlight {
    scrollbar-gutter: stable;
}`
