### ISSUE TITLE
Gallery functionality not working

### ISSUE THREAD

**Issue by zopyx** [noelboss/featherlight#378]
Using Featherlight+gallery on 

https://beta.print-css.rocks/lesson/lesson-basic

The page has three different galleries and their markup looks like this.
However the gallery functionality is not working, only the standard Featherlight functionality is working.

Using latest 1.7.3 version.

```
<td data-featherlight-gallery="" data-featherlight-filter="a">                      
    <a href="#" class="gallery-pdfreactor" data-featherlight="https://beta.print-css.rocks/lesson/lesson-basic/download/images/pdfreactor/pdfreactor-0.png">
          <img class="preview" src="https://beta.print-css.rocks/lesson/lesson-basic/download/images/pdfreactor/thumb-pdfreactor-0.png">
     </a>                           
     <a href="#" class="gallery-pdfreactor" data-featherlight="https://beta.print-css.rocks/lesson/lesson-basic/download/images/pdfreactor/pdfreactor-1.png">
          <img class="preview" src="https://beta.print-css.rocks/lesson/lesson-basic/download/images/pdfreactor/thumb-pdfreactor-1.png">
   </a>                    
</td>

```

**Comment by marcandre** [comment]
Sorry you're having troubles.

Issues are to be opened for bugs in the library, not for users having troubles in using it correctly.

If you believe there is an actual bug, please provide a minimal example. Otherwise you'll need to find the issue yourself, ask for help on StackOverflow, hire me, etc. Good luck

**Comment by zopyx** [comment]
Thanks. i will move on go a different solution where the author does not behave like a bitchy diva 🤣
