### ISSUE TITLE
Rawgit end of life

### ISSUE THREAD

**Issue by COil** [noelboss/featherlight#387]
https://rawgit.com/  will stop working at least October of 2019.

URLs should be changed. For example : 

* https://cdn.jsdelivr.net/gh/noelboss/featherlight@master/src/featherlight.css
* https://cdn.jsdelivr.net/gh/noelboss/featherlight@master/src/featherlight.js

There is a converter for jsdelivr : 

https://www.jsdelivr.com/rawgit

See you.

**Comment by marcandre** [comment]
Should be fixed now, thanks.
