### ISSUE TITLE
Rawgit cdn

### ISSUE THREAD

**Issue by pearllemon** [noelboss/featherlight#393]
What kind of issue is this? (put 'x' between the square brackets)

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use
       http://stackoverflow.com/questions/ask .
       Provide working code, starting from http://jsfiddle.net/JNsu6/15/.
       We monitor the tag `featherlight.js`.

 - [ ] Bug report. If you’ve found a bug, you must provide a minimal example in a CodePen,
       starting from http://jsfiddle.net/JNsu6/15/ .

 - [X ] Feature Request. Make sure there's no good way to do what you want first;
       consider asking on http://stackoverflow.com/questions/ask first.

The current cdn uses rawgit to serve the js which is going to be shut down soon. Have you got an alternative cdn ie from githubpages or something?

**Comment by marcandre** [comment]
Sorry, Ive been traveling a lot these past months and haven't had the time to look into this yet...

**Comment by marcandre** [comment]
Should be fixed now, thanks.
