### ISSUE TITLE
CDN not working 

### ISSUE THREAD

**Issue by donprecious** [noelboss/featherlight#400]
cdn.rawgit.com/noelboss/featherlight/1.7.14/release/featherlight.min.css 

return 404

**Comment by inverse** [comment]
rawgit as EOL since October. 

See: https://rawgit.com/

**Comment by samdb** [comment]
The same code is available on other CDNs. I have proposed an update to the README in #402

**Comment by marcandre** [comment]
Should be fixed now, thanks.
