### ISSUE TITLE
Popup Modal appears on mobile

### ISSUE THREAD

**Issue by loretog** [noelboss/featherlight#406]
- Bug report. 

Popup Modal appears when screen is 768px and below

http://prntscr.com/rmr7yb

https://www.digitalcreationacademy.com/cheat-sheet-opt-in-test/
pass: test1

Fix:

CSS
.popup-modal { display: none; }

JS
`jQuery(function() {
	//if( jQuery( ".page-id-37" ).length ) {  // specific page
	  jQuery(document).on('click', '.button', function () {
	    jQuery( ".popup-modal" ).css( 'display', 'block' );
	  });
		jQuery(document).on('click', '.featherlight-close', function () {
		  jQuery( ".popup-modal" ).css( 'display', 'none' );
		});
	//}
});`

**Comment by marcandre** [comment]
I'm sorry, I don't see how that would be a Featherlight bug. If you remove the library from your page you will still have the exact same issue!
Good luck
