### ISSUE TITLE
Light box does not seem to work with dynamically created image links in Spring/Thymeleaf

### ISSUE THREAD

**Issue by mydogspies** [noelboss/featherlight#408]
I am using the Featherlight gallery/lightbox combo in a Spring app with Thymeleaf. Using standard Thymeleaf markup I create dynamic urls that look like the following example pattern "http://host/gallery/image/2", using Spring HttpServerResponse with "image/jpeg" as content type. Below the html part of the code.

`<div id="macy-container" data-featherlight-gallery data-featherlight-filter="a" data-featherlight-type="image">
    <div class="masonry-content" th:each="content : ${contentList}">
        <div class="macy-item">
            <a th:href="@{'/gallery/image/' + ${content.id}}" class="gallery2">
                <img th:src="@{'/gallery/image/' + ${content.id}}" width="225" class="macy-image" alt="image"/>
            </a>
        </div>
    </div>
    </div>`

This works perfectly fine with the Featherlight Gallery component and I get a nice masonry layout with the images loaded. The browser also recognizes the URL created by Spring as an image if I call it direct.

But when clicked on any image, the light box opens with raw byte code, not the image itself. It's obvious the link is correct but the light box component does not recognize the content as an image. I am guess that either something is missing in the image information that Spring creates or the light box code s missing something that the gallery is not.

The above code works perfectly fine if I substitute the Thymeleaf markup with hard coded URLs to some location with images.

I also posted this problem on [Stackoverflow](https://stackoverflow.com/questions/63810830/featherlight-lighbox-together-with-spring-and-thymeleaf-does-not-open-image-in-b) not knowing if this a bug or just me missing some configuration. Find it bit strange though that the gallery has no issues when the light box does so thus posting here too.

**Comment by marcandre** [comment]
Using `data-featherlight-type="image"` should be the best solution.

I'm sorry, it's not clear at first sight what the issue is.

**Comment by mydogspies** [comment]
The issue is that the gallery built by Featherlight shows the images properly;
![gallery](https://user-images.githubusercontent.com/18701250/92687755-68cbde80-f33c-11ea-81fe-0accbff03119.jpg)

But when I click on an image to open it in a light box, it only shows the raw code, not the image;
![light_box](https://user-images.githubusercontent.com/18701250/92687824-8600ad00-f33c-11ea-9a34-c3fcd0021bc9.jpg)

The actual html code of that gallery is;
` <div id="macy-container" data-featherlight-gallery data-featherlight-filter="a" data-featherlight-type="image">
    <div class="masonry-content">
        <div class="macy-item">
            <a href="/gallery/image/5" class="gallery2">
                <img src="/gallery/image/5" width="225" class="macy-image" alt="image"/>
            </a>
        </div>
    </div>
    <div class="masonry-content">
        <div class="macy-item">
            <a href="/gallery/image/2" class="gallery2">
                <img src="/gallery/image/2" width="225" class="macy-image" alt="image"/>
            </a>
        </div>
    </div>
    <div class="masonry-content">
        <div class="macy-item">
            <a href="/gallery/image/3" class="gallery2">
                <img src="/gallery/image/3" width="225" class="macy-image" alt="image"/>
            </a>
        </div>
    </div>
    </div>`

So it seems to me that the gallery component gets it that "/gallery/image/5" is an image and renders it as such while the light box component does not and renders garbage. And I am using data-featherlight-type="image"

**Comment by mydogspies** [comment]
OK, this happens when I try to instantiate via JQuery;

`$('.gallery2').featherlightGallery({
        variant: 'featherlight-gallery2'
    });`

Was trying this in order to simply switch between your css styles while testing. As soon as I take the call out, all works well.
