### ISSUE TITLE
Big images

### ISSUE THREAD

**Issue by marcandre** [noelboss/featherlight#43]
Two issues with big images (i.e. images that won't fit the current window) in `featherlight`.

The main issue is that if the image doesn't fit width-wise, it will be resized (great!), but if it doesn't fit height-wise, it gets cut and one needs to scroll.

It makes sense for a general lightbox to allow scrolling but for images it's not really what we want (or at least what I want :smiley: ).

My CSS skills aren't good enough to find a solution (either for a wiki entry or modification of the official css). I played around a bit and tried clearing `width` and setting both `max-width` and `max-height` to 100% but it doesn't quite work. Somehow the height is too big.

The second issue is that the behavior for IE (at least for IE 9) is different, and the image [gets squished](http://cl.ly/image/0B1H0b0F2t0q).

@noelboss can you find a solution for these?

**Comment by Barzille** [comment]
What if we change this css behaviour?

	.featherlight .featherlight-image {
		/* styling */
		/*width: 100%;*/
		max-width:100%;
		max-height:100%;
	}
Won't that help?

**Comment by Barzille** [comment]
Is there a (final) solution on the horizon? Will featherlight be updated to have the image fit completely into the lightbox?

**Comment by Barzille** [comment]
I have a small JS solution, which is not perfect and is a little jumpy. Simply change the afterOpen and afterClose methods to the following:

    afterOpen:    function(event){
		 var $flc = $(".featherlight-content");
		var featherLightImage = $flc.find('img');
		var imageRatio = featherLightImage.width() / featherLightImage.height();
     		$flc.css('height',$flc.height()+'px');
     		$flc.css('width',$flc.height()*imageRatio+'px');
    },
    afterClose:   function(event){
		$(".featherlight-content").css('height','');
		$(".featherlight-content").css('width','');
    },

**Comment by DoubleElite** [comment]
Do we have a solution to this? I don't want large images to have to be scrolled.

**Comment by marcandre** [comment]
I'm actively working on a solution for this, hope to get it out in a few days.

**Comment by StudioJunkyard** [comment]
+1

**Comment by marcandre** [comment]
Merged in master, should release shortly.

**Comment by robneu** [comment]
:100: x1000 :+1:

**Comment by elixirgraphics** [comment]
I've been experiencing scroll bars on vertical images that don't fit within the viewport as well. Using v1.2.3, which I'm assuming is the latest master branch, and still have the problem. Anyone else still having this happen as well?

**Comment by marcandre** [comment]
@elixirgraphics Probably the issue with bootstrap which I haven't checked yet. See #117 for a solution.

**Comment by elixirgraphics** [comment]
Actually it seems that when you use inline options the scroll bar comes back. If I remove the `data-featherlight-close-icon` inline option from my image link the problem goes away.

**Comment by MickeyKay** [comment]
Any progress on this one?

**Comment by marcandre** [comment]
@MickeyKay this issue is closed...

**Comment by MickeyKay** [comment]
Right, I saw that. But the issue is not resolved and I can't find a full-on explanation of resolution elsewhere. Please see #166 for the same issue still happening.

**Comment by KodeStar** [comment]
_callbackChain onResize function (near the bottom of plugins.js line 569)

Change:

    if (ratio > 1) {
        this.$content.css('width', '' + w / ratio + 'px').css('height', '' + h / ratio + 'px');
    }

to

    if (ratio > 1) {
        this.$content.css('width', '' + w / ratio - 50 + 'px').css('height', '' + h / ratio - 50 + 'px');
    }

The 50 is to take into account the padding (25 top + 25 bottom and 25 left + 25 right)

**Comment by mweimerskirch** [comment]
Thanks @KodeStar, that fixes the issue for me as well.

**Comment by stevenbuccini** [comment]
Is this project still maintained? @KodeStar's snippet fixed the issue for me as well, and I'm surprised it hasn't been merged to master. Happy to whip up a PR if a maintainer will accept it.

cc @marcandre, @noelboss

**Comment by marcandre** [comment]
I'll definitely accept a PR, but would be best without the hardcoded "50"s, and instead getting those from the CSS somehow

**Comment by madmax2000** [comment]
.featherlight-image {
    width: auto !important;
    height: auto !important;
    max-width: 100%;
    max-height: 90vh;
}

This small css changes does the trick. No scrollbars anymore :) 
Test around with max-height: 90vh and less for smartphones.
