### ISSUE TITLE
Image alt as a description

### ISSUE THREAD

**Issue by Libig** [noelboss/featherlight#70]
The gallery works fine, however there is no option to display a description in modal.

**Comment by Zdunek** [comment]
New version Featherlight don't have afterSlide()
How to do something like that?

**Comment by marcandre** [comment]
Sorry, it has been renamed `afterContent`

**Comment by marcandre** [comment]
And `$elm` is no more. I updated the wiki.

**Comment by Zdunek** [comment]
Thank you very much!

**Comment by Fruchuxs** [comment]
The Problem with the caption solution is, that the text will expand the feather-light container and the image.

**Comment by marcandre** [comment]
@Fruchuxs Yes, you'll have to decide how you want to show the caption and adapt the CSS accordingly.

**Comment by foria** [comment]
Hi.
I'm trying to use the code above but it doesn't work.
Here how I implemented it:
`$('.collection-color-list a').featherlightGallery({
	        previousIcon: '',
	        nextIcon: '',
	        galleryFadeIn: 300,
	        openSpeed: 300,
	        afterOpen: function(event){
				var caption = this.$currentTarget.find('img').attr('alt');
				this.$instance.find('.caption').remove();
				$('<div class="caption">').text(caption).appendTo(this.$instance.find('.featherlight-content'));
			}
	    });`

can you help me please? Thx

**Comment by foria** [comment]
I fix the problem and now I get the caption in the gallery but it's useless because on image change it doesn't update the caption.
Is there an event to fire the change of the image in the gallery?
Thx

**Comment by marcandre** [comment]
@foria: Answer already in this thread. Questions on SO please

**Comment by foria** [comment]
@marcandre if you mean afterContent() event trigger it doesn't work. Thank you but I don't know what SO is.
