### ISSUE TITLE
When another web page is loaded in an iframe is it touch / swipe capable for scrolling?

### ISSUE THREAD

**Issue by SavaTom** [noelboss/featherlight#77]

**Comment by keithslater** [comment]
In case anyone else is looking for the answer - it doesn't. It scroll the parent page behind it.

**Comment by kenderson** [comment]
I am having the same issue here. Scrolls and works great on a desktop, but scrolling/swiping doesnt seem to work on a mobile device.

**Comment by marcandre** [comment]
Anyone knows how to address this?

**Comment by leowski** [comment]
I have the same issue here. It's impossible to scroll in the Iframe with a mobile device

**Comment by VanDerLars** [comment]
same here

**Comment by marcandre** [comment]
I'm very sorry I don't have time/need to investigate this but hopefully someone will come up with a good solution to this?

**Comment by jphilung** [comment]
The problem lies with how iOS Safari handles overflow on scroll. Safari iOS requires the following CSS:

```
-webkit-overflow-scrolling: touch;
overflow-y: scroll;

```

https://css-tricks.com/forums/topic/scrolling-iframe-on-ipad/
https://davidwalsh.name/scroll-iframes-ios

**Comment by marcandre** [comment]
Sounds great @jphilung , do you have a second or two to create a PR?

**Comment by marcandre** [comment]
Released in 1.7.0. Many thanks to @jphilung
