### ISSUE TITLE
Can't seem to make multiple independent galleries on one page...

### ISSUE THREAD

**Issue by nicolaseckhart** [noelboss/featherlight#95]
If I try to make two galleries (gallery A with pics 1-3, and gallery B with pics 4-6), and then open A, then I can also click through the pictures from B. Is this an issue, and if not, how do I get around it?

**Comment by bartulans** [comment]
Hello,

It seams it doesn't work for me, or I'm missing the point. Please help, my code is below.
<section data-featherlight-gallery data-featherlight-filter="225">
<div class="col-lg-4">
<a class="thumbnail gallery 225" href="..." style="background: url(...);"></a>
</div>
<section>
Thanks

**Comment by marcandre** [comment]
Filter should be `".225"` I think. If not, please open new issue...
